#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "../models/credit_note" 
require "../models/credit_note_line_item_params" 
require "../models/credit_note_lines_list" 
require "../models/credit_note_refund_params" 
require "../models/credit_note_shipping_cost" 
require "../models/credit_notes_list" 
require "../models/error" 
require "../models/get_accounts_created_parameter" 


module Stripe
  class CreditNotesApi
    property api_client : ApiClient

    delegate client_side_validation?, debugging?, to: @api_client.config

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # List all credit notes
    # <p>Returns a list of credit notes.</p>
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param customer [String?] Only return credit notes for the customer specified by this customer ID.
    # @optional @param invoice [String?] Only return credit notes for the invoice specified by this invoice ID.
    # @optional @param created [Stripe::GetAccountsCreatedParameter?] Only return credit notes that were created during the given date interval.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return [Stripe::CreditNotesList]
    def get_credit_notes(
      *, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      customer : String? = nil, 
      invoice : String? = nil, 
      created : Stripe::GetAccountsCreatedParameter? = nil, 
      expand : Array(Array(String))? = nil
    ) : Stripe::CreditNotesList
      data, _status_code, _headers = get_credit_notes_with_http_info(ending_before: ending_before, starting_after: starting_after, limit: limit, customer: customer, invoice: invoice, created: created, expand: expand)
      data
    end

    # List all credit notes
    # &lt;p&gt;Returns a list of credit notes.&lt;/p&gt;
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param customer [String?] Only return credit notes for the customer specified by this customer ID.
    # @optional @param invoice [String?] Only return credit notes for the invoice specified by this invoice ID.
    # @optional @param created [Stripe::GetAccountsCreatedParameter?] Only return credit notes that were created during the given date interval.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return [Tuple(Stripe::CreditNotesList, Integer, Hash)] Stripe::CreditNotesList, response status code and response headers
    def get_credit_notes_with_http_info(
      *, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      customer : String? = nil, 
      invoice : String? = nil, 
      created : Stripe::GetAccountsCreatedParameter? = nil, 
      expand : Array(Array(String))? = nil
    ) : Tuple(Stripe::CreditNotesList, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_get_credit_notes(ending_before: ending_before, starting_after: starting_after, limit: limit, customer: customer, invoice: invoice, created: created, expand: expand)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#get_credit_notes\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNotesList.from_json(body), status_code, headers)
    end

    # List all credit notes
    # &lt;p&gt;Returns a list of credit notes.&lt;/p&gt;
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param customer [String?] Only return credit notes for the customer specified by this customer ID.
    # @optional @param invoice [String?] Only return credit notes for the invoice specified by this invoice ID.
    # @optional @param created [Stripe::GetAccountsCreatedParameter?] Only return credit notes that were created during the given date interval.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return nil
    def get_credit_notes(
      *,
      ending_before : String? = nil,
      starting_after : String? = nil,
      limit : Int32? = nil,
      customer : String? = nil,
      invoice : String? = nil,
      created : Stripe::GetAccountsCreatedParameter? = nil,
      expand : Array(Array(String))? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_get_credit_notes(ending_before: ending_before, starting_after: starting_after, limit: limit, customer: customer, invoice: invoice, created: created, expand: expand).execute(&block)
    end

    GET_CREDIT_NOTES_MAX_LENGTH_FOR_ENDING_BEFORE = 5000
    GET_CREDIT_NOTES_MAX_LENGTH_FOR_STARTING_AFTER = 5000
    GET_CREDIT_NOTES_MAX_LENGTH_FOR_CUSTOMER = 5000
    GET_CREDIT_NOTES_MAX_LENGTH_FOR_INVOICE = 5000
    # @return Crest::Request
    def build_api_request_for_get_credit_notes(
      *, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      customer : String? = nil, 
      invoice : String? = nil, 
      created : Stripe::GetAccountsCreatedParameter? = nil, 
      expand : Array(Array(String))? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.get_credit_notes ..." }
      end

      if client_side_validation?
        unless (_ending_before = ending_before).nil?
          OpenApi::PrimitiveValidator.validate_max_length("ending_before", ending_before.to_s.size, GET_CREDIT_NOTES_MAX_LENGTH_FOR_ENDING_BEFORE)
        end
        unless (_starting_after = starting_after).nil?
          OpenApi::PrimitiveValidator.validate_max_length("starting_after", starting_after.to_s.size, GET_CREDIT_NOTES_MAX_LENGTH_FOR_STARTING_AFTER)
        end
        unless (_limit = limit).nil?
        end
        unless (_customer = customer).nil?
          OpenApi::PrimitiveValidator.validate_max_length("customer", customer.to_s.size, GET_CREDIT_NOTES_MAX_LENGTH_FOR_CUSTOMER)
        end
        unless (_invoice = invoice).nil?
          OpenApi::PrimitiveValidator.validate_max_length("invoice", invoice.to_s.size, GET_CREDIT_NOTES_MAX_LENGTH_FOR_INVOICE)
        end
        unless (_created = created).nil?
          _created.validate if _created.is_a?(OpenApi::Validatable)
        end
        unless (_expand = expand).nil?
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes"

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new
      query_params["ending_before"] = ending_before.to_s if !ending_before.nil?
      query_params["starting_after"] = starting_after.to_s if !starting_after.nil?
      query_params["limit"] = limit.to_s if !limit.nil?
      query_params["customer"] = customer.to_s if !customer.nil?
      query_params["invoice"] = invoice.to_s if !invoice.nil?
      query_params["created"] = created.to_s if !created.nil?
      query_params["expand"] = @api_client.build_collection_param(expand, "csv") if !expand.nil? && !expand.empty?

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = nil

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"GET",
        path: local_var_path,
        operation: "CreditNotesApi.get_credit_notes",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Retrieve a credit note's line items
    # <p>When retrieving a credit note, you’ll get a <strong>lines</strong> property containing the first handful of those items. There is also a URL where you can retrieve the full (paginated) list of line items.</p>
    # @required @param credit_note [String?]
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return [Stripe::CreditNoteLinesList]
    def get_credit_notes_credit_note_lines(
      *, 
      credit_note : String? = nil, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      expand : Array(Array(String))? = nil
    ) : Stripe::CreditNoteLinesList
      data, _status_code, _headers = get_credit_notes_credit_note_lines_with_http_info(credit_note: credit_note, ending_before: ending_before, starting_after: starting_after, limit: limit, expand: expand)
      data
    end

    # Retrieve a credit note&#39;s line items
    # &lt;p&gt;When retrieving a credit note, you’ll get a &lt;strong&gt;lines&lt;/strong&gt; property containing the first handful of those items. There is also a URL where you can retrieve the full (paginated) list of line items.&lt;/p&gt;
    # @required @param credit_note [String?]
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return [Tuple(Stripe::CreditNoteLinesList, Integer, Hash)] Stripe::CreditNoteLinesList, response status code and response headers
    def get_credit_notes_credit_note_lines_with_http_info(
      *, 
      credit_note : String? = nil, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      expand : Array(Array(String))? = nil
    ) : Tuple(Stripe::CreditNoteLinesList, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_get_credit_notes_credit_note_lines(credit_note: credit_note, ending_before: ending_before, starting_after: starting_after, limit: limit, expand: expand)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#get_credit_notes_credit_note_lines\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNoteLinesList.from_json(body), status_code, headers)
    end

    # Retrieve a credit note&#39;s line items
    # &lt;p&gt;When retrieving a credit note, you’ll get a &lt;strong&gt;lines&lt;/strong&gt; property containing the first handful of those items. There is also a URL where you can retrieve the full (paginated) list of line items.&lt;/p&gt;
    # @required @param credit_note [String?]
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return nil
    def get_credit_notes_credit_note_lines(
      *,
      credit_note : String? = nil,
      ending_before : String? = nil,
      starting_after : String? = nil,
      limit : Int32? = nil,
      expand : Array(Array(String))? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_get_credit_notes_credit_note_lines(credit_note: credit_note, ending_before: ending_before, starting_after: starting_after, limit: limit, expand: expand).execute(&block)
    end

    GET_CREDIT_NOTES_CREDIT_NOTE_LINES_MAX_LENGTH_FOR_CREDIT_NOTE = 5000
    GET_CREDIT_NOTES_CREDIT_NOTE_LINES_MAX_LENGTH_FOR_ENDING_BEFORE = 5000
    GET_CREDIT_NOTES_CREDIT_NOTE_LINES_MAX_LENGTH_FOR_STARTING_AFTER = 5000
    # @return Crest::Request
    def build_api_request_for_get_credit_notes_credit_note_lines(
      *, 
      credit_note : String? = nil, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      expand : Array(Array(String))? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.get_credit_notes_credit_note_lines ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"credit_note\" is required and cannot be null") if credit_note.nil?
        unless (_credit_note = credit_note).nil?
          OpenApi::PrimitiveValidator.validate_max_length("credit_note", credit_note.to_s.size, GET_CREDIT_NOTES_CREDIT_NOTE_LINES_MAX_LENGTH_FOR_CREDIT_NOTE)
        end
        unless (_ending_before = ending_before).nil?
          OpenApi::PrimitiveValidator.validate_max_length("ending_before", ending_before.to_s.size, GET_CREDIT_NOTES_CREDIT_NOTE_LINES_MAX_LENGTH_FOR_ENDING_BEFORE)
        end
        unless (_starting_after = starting_after).nil?
          OpenApi::PrimitiveValidator.validate_max_length("starting_after", starting_after.to_s.size, GET_CREDIT_NOTES_CREDIT_NOTE_LINES_MAX_LENGTH_FOR_STARTING_AFTER)
        end
        unless (_limit = limit).nil?
        end
        unless (_expand = expand).nil?
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes/{credit_note}/lines".sub("{" + "credit_note" + "}", URI.encode_path(credit_note.to_s))

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new
      query_params["ending_before"] = ending_before.to_s if !ending_before.nil?
      query_params["starting_after"] = starting_after.to_s if !starting_after.nil?
      query_params["limit"] = limit.to_s if !limit.nil?
      query_params["expand"] = @api_client.build_collection_param(expand, "csv") if !expand.nil? && !expand.empty?

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = nil

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"GET",
        path: local_var_path,
        operation: "CreditNotesApi.get_credit_notes_credit_note_lines",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Retrieve a credit note
    # <p>Retrieves the credit note object with the given identifier.</p>
    # @required @param id [String?]
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return [Stripe::CreditNote]
    def get_credit_notes_id(
      *, 
      id : String? = nil, 
      expand : Array(Array(String))? = nil
    ) : Stripe::CreditNote
      data, _status_code, _headers = get_credit_notes_id_with_http_info(id: id, expand: expand)
      data
    end

    # Retrieve a credit note
    # &lt;p&gt;Retrieves the credit note object with the given identifier.&lt;/p&gt;
    # @required @param id [String?]
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return [Tuple(Stripe::CreditNote, Integer, Hash)] Stripe::CreditNote, response status code and response headers
    def get_credit_notes_id_with_http_info(
      *, 
      id : String? = nil, 
      expand : Array(Array(String))? = nil
    ) : Tuple(Stripe::CreditNote, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_get_credit_notes_id(id: id, expand: expand)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#get_credit_notes_id\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNote.from_json(body), status_code, headers)
    end

    # Retrieve a credit note
    # &lt;p&gt;Retrieves the credit note object with the given identifier.&lt;/p&gt;
    # @required @param id [String?]
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @return nil
    def get_credit_notes_id(
      *,
      id : String? = nil,
      expand : Array(Array(String))? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_get_credit_notes_id(id: id, expand: expand).execute(&block)
    end

    GET_CREDIT_NOTES_ID_MAX_LENGTH_FOR_ID = 5000
    # @return Crest::Request
    def build_api_request_for_get_credit_notes_id(
      *, 
      id : String? = nil, 
      expand : Array(Array(String))? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.get_credit_notes_id ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"id\" is required and cannot be null") if id.nil?
        unless (_id = id).nil?
          OpenApi::PrimitiveValidator.validate_max_length("id", id.to_s.size, GET_CREDIT_NOTES_ID_MAX_LENGTH_FOR_ID)
        end
        unless (_expand = expand).nil?
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new
      query_params["expand"] = @api_client.build_collection_param(expand, "csv") if !expand.nil? && !expand.empty?

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = nil

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"GET",
        path: local_var_path,
        operation: "CreditNotesApi.get_credit_notes_id",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Preview a credit note
    # <p>Get a preview of a credit note without creating it.</p>
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param lines [Array(Array(CreditNoteLineItemParams))?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refunds [Array(Array(CreditNoteRefundParams))?] Refunds to link to this credit note.
    # @optional @param metadata [Hash(String, Hash(String, String))?] Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?] When shipping_cost contains the shipping_rate from the invoice, the shipping_cost is included in the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @return [Stripe::CreditNote]
    def get_credit_notes_preview(
      *, 
      invoice : String? = nil, 
      lines : Array(Array(CreditNoteLineItemParams))? = nil, 
      reason : String? = nil, 
      refunds : Array(Array(CreditNoteRefundParams))? = nil, 
      metadata : Hash(String, Hash(String, String))? = nil, 
      expand : Array(Array(String))? = nil, 
      memo : String? = nil, 
      effective_at : Int32? = nil, 
      out_of_band_amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      refund_amount : Int32? = nil, 
      amount : Int32? = nil, 
      email_type : String? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Stripe::CreditNote
      data, _status_code, _headers = get_credit_notes_preview_with_http_info(invoice: invoice, lines: lines, reason: reason, refunds: refunds, metadata: metadata, expand: expand, memo: memo, effective_at: effective_at, out_of_band_amount: out_of_band_amount, credit_amount: credit_amount, refund_amount: refund_amount, amount: amount, email_type: email_type, shipping_cost: shipping_cost)
      data
    end

    # Preview a credit note
    # &lt;p&gt;Get a preview of a credit note without creating it.&lt;/p&gt;
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param lines [Array(Array(CreditNoteLineItemParams))?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refunds [Array(Array(CreditNoteRefundParams))?] Refunds to link to this credit note.
    # @optional @param metadata [Hash(String, Hash(String, String))?] Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?] When shipping_cost contains the shipping_rate from the invoice, the shipping_cost is included in the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @return [Tuple(Stripe::CreditNote, Integer, Hash)] Stripe::CreditNote, response status code and response headers
    def get_credit_notes_preview_with_http_info(
      *, 
      invoice : String? = nil, 
      lines : Array(Array(CreditNoteLineItemParams))? = nil, 
      reason : String? = nil, 
      refunds : Array(Array(CreditNoteRefundParams))? = nil, 
      metadata : Hash(String, Hash(String, String))? = nil, 
      expand : Array(Array(String))? = nil, 
      memo : String? = nil, 
      effective_at : Int32? = nil, 
      out_of_band_amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      refund_amount : Int32? = nil, 
      amount : Int32? = nil, 
      email_type : String? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Tuple(Stripe::CreditNote, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_get_credit_notes_preview(invoice: invoice, lines: lines, reason: reason, refunds: refunds, metadata: metadata, expand: expand, memo: memo, effective_at: effective_at, out_of_band_amount: out_of_band_amount, credit_amount: credit_amount, refund_amount: refund_amount, amount: amount, email_type: email_type, shipping_cost: shipping_cost)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#get_credit_notes_preview\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNote.from_json(body), status_code, headers)
    end

    # Preview a credit note
    # &lt;p&gt;Get a preview of a credit note without creating it.&lt;/p&gt;
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param lines [Array(Array(CreditNoteLineItemParams))?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refunds [Array(Array(CreditNoteRefundParams))?] Refunds to link to this credit note.
    # @optional @param metadata [Hash(String, Hash(String, String))?] Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?] When shipping_cost contains the shipping_rate from the invoice, the shipping_cost is included in the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @return nil
    def get_credit_notes_preview(
      *,
      invoice : String? = nil,
      lines : Array(Array(CreditNoteLineItemParams))? = nil,
      reason : String? = nil,
      refunds : Array(Array(CreditNoteRefundParams))? = nil,
      metadata : Hash(String, Hash(String, String))? = nil,
      expand : Array(Array(String))? = nil,
      memo : String? = nil,
      effective_at : Int32? = nil,
      out_of_band_amount : Int32? = nil,
      credit_amount : Int32? = nil,
      refund_amount : Int32? = nil,
      amount : Int32? = nil,
      email_type : String? = nil,
      shipping_cost : Stripe::CreditNoteShippingCost? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_get_credit_notes_preview(invoice: invoice, lines: lines, reason: reason, refunds: refunds, metadata: metadata, expand: expand, memo: memo, effective_at: effective_at, out_of_band_amount: out_of_band_amount, credit_amount: credit_amount, refund_amount: refund_amount, amount: amount, email_type: email_type, shipping_cost: shipping_cost).execute(&block)
    end

    GET_CREDIT_NOTES_PREVIEW_MAX_LENGTH_FOR_INVOICE = 5000
    GET_CREDIT_NOTES_PREVIEW_VALID_VALUES_FOR_REASON = String.static_array("duplicate", "fraudulent", "order_change", "product_unsatisfactory")
    GET_CREDIT_NOTES_PREVIEW_MAX_LENGTH_FOR_MEMO = 5000
    GET_CREDIT_NOTES_PREVIEW_VALID_VALUES_FOR_EMAIL_TYPE = String.static_array("credit_note", "none")
    # @return Crest::Request
    def build_api_request_for_get_credit_notes_preview(
      *, 
      invoice : String? = nil, 
      lines : Array(Array(CreditNoteLineItemParams))? = nil, 
      reason : String? = nil, 
      refunds : Array(Array(CreditNoteRefundParams))? = nil, 
      metadata : Hash(String, Hash(String, String))? = nil, 
      expand : Array(Array(String))? = nil, 
      memo : String? = nil, 
      effective_at : Int32? = nil, 
      out_of_band_amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      refund_amount : Int32? = nil, 
      amount : Int32? = nil, 
      email_type : String? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.get_credit_notes_preview ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"invoice\" is required and cannot be null") if invoice.nil?
        unless (_invoice = invoice).nil?
          OpenApi::PrimitiveValidator.validate_max_length("invoice", invoice.to_s.size, GET_CREDIT_NOTES_PREVIEW_MAX_LENGTH_FOR_INVOICE)
        end
        unless (_lines = lines).nil?
        end
        unless (_reason = reason).nil?
          OpenApi::EnumValidator.validate("reason", _reason, GET_CREDIT_NOTES_PREVIEW_VALID_VALUES_FOR_REASON)
        end
        unless (_refunds = refunds).nil?
        end
        unless (_metadata = metadata).nil?
        end
        unless (_expand = expand).nil?
        end
        unless (_memo = memo).nil?
          OpenApi::PrimitiveValidator.validate_max_length("memo", memo.to_s.size, GET_CREDIT_NOTES_PREVIEW_MAX_LENGTH_FOR_MEMO)
        end
        unless (_effective_at = effective_at).nil?
        end
        unless (_out_of_band_amount = out_of_band_amount).nil?
        end
        unless (_credit_amount = credit_amount).nil?
        end
        unless (_refund_amount = refund_amount).nil?
        end
        unless (_amount = amount).nil?
        end
        unless (_email_type = email_type).nil?
          OpenApi::EnumValidator.validate("email_type", _email_type, GET_CREDIT_NOTES_PREVIEW_VALID_VALUES_FOR_EMAIL_TYPE)
        end
        unless (_shipping_cost = shipping_cost).nil?
          _shipping_cost.validate if _shipping_cost.is_a?(OpenApi::Validatable)
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes/preview"

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new
      query_params["invoice"] = invoice.to_s if !invoice.nil?
      query_params["lines"] = @api_client.build_collection_param(lines, "csv") if !lines.nil? && !lines.empty?
      query_params["reason"] = reason.to_s if !reason.nil?
      query_params["refunds"] = @api_client.build_collection_param(refunds, "csv") if !refunds.nil? && !refunds.empty?
      query_params["metadata"] = metadata.to_s if !metadata.nil?
      query_params["expand"] = @api_client.build_collection_param(expand, "csv") if !expand.nil? && !expand.empty?
      query_params["memo"] = memo.to_s if !memo.nil?
      query_params["effective_at"] = effective_at.to_s if !effective_at.nil?
      query_params["out_of_band_amount"] = out_of_band_amount.to_s if !out_of_band_amount.nil?
      query_params["credit_amount"] = credit_amount.to_s if !credit_amount.nil?
      query_params["refund_amount"] = refund_amount.to_s if !refund_amount.nil?
      query_params["amount"] = amount.to_s if !amount.nil?
      query_params["email_type"] = email_type.to_s if !email_type.nil?
      query_params["shipping_cost"] = shipping_cost.to_s if !shipping_cost.nil?

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = nil

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"GET",
        path: local_var_path,
        operation: "CreditNotesApi.get_credit_notes_preview",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Retrieve a credit note preview's line items
    # <p>When retrieving a credit note preview, you’ll get a <strong>lines</strong> property containing the first handful of those items. This URL you can retrieve the full (paginated) list of line items.</p>
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param lines [Array(Array(CreditNoteLineItemParams))?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refunds [Array(Array(CreditNoteRefundParams))?] Refunds to link to this credit note.
    # @optional @param metadata [Hash(String, Hash(String, String))?] Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?] When shipping_cost contains the shipping_rate from the invoice, the shipping_cost is included in the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @return [Stripe::CreditNoteLinesList]
    def get_credit_notes_preview_lines(
      *, 
      invoice : String? = nil, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      lines : Array(Array(CreditNoteLineItemParams))? = nil, 
      reason : String? = nil, 
      refunds : Array(Array(CreditNoteRefundParams))? = nil, 
      metadata : Hash(String, Hash(String, String))? = nil, 
      expand : Array(Array(String))? = nil, 
      memo : String? = nil, 
      effective_at : Int32? = nil, 
      out_of_band_amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      refund_amount : Int32? = nil, 
      amount : Int32? = nil, 
      email_type : String? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Stripe::CreditNoteLinesList
      data, _status_code, _headers = get_credit_notes_preview_lines_with_http_info(invoice: invoice, ending_before: ending_before, starting_after: starting_after, limit: limit, lines: lines, reason: reason, refunds: refunds, metadata: metadata, expand: expand, memo: memo, effective_at: effective_at, out_of_band_amount: out_of_band_amount, credit_amount: credit_amount, refund_amount: refund_amount, amount: amount, email_type: email_type, shipping_cost: shipping_cost)
      data
    end

    # Retrieve a credit note preview&#39;s line items
    # &lt;p&gt;When retrieving a credit note preview, you’ll get a &lt;strong&gt;lines&lt;/strong&gt; property containing the first handful of those items. This URL you can retrieve the full (paginated) list of line items.&lt;/p&gt;
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param lines [Array(Array(CreditNoteLineItemParams))?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refunds [Array(Array(CreditNoteRefundParams))?] Refunds to link to this credit note.
    # @optional @param metadata [Hash(String, Hash(String, String))?] Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?] When shipping_cost contains the shipping_rate from the invoice, the shipping_cost is included in the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @return [Tuple(Stripe::CreditNoteLinesList, Integer, Hash)] Stripe::CreditNoteLinesList, response status code and response headers
    def get_credit_notes_preview_lines_with_http_info(
      *, 
      invoice : String? = nil, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      lines : Array(Array(CreditNoteLineItemParams))? = nil, 
      reason : String? = nil, 
      refunds : Array(Array(CreditNoteRefundParams))? = nil, 
      metadata : Hash(String, Hash(String, String))? = nil, 
      expand : Array(Array(String))? = nil, 
      memo : String? = nil, 
      effective_at : Int32? = nil, 
      out_of_band_amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      refund_amount : Int32? = nil, 
      amount : Int32? = nil, 
      email_type : String? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Tuple(Stripe::CreditNoteLinesList, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_get_credit_notes_preview_lines(invoice: invoice, ending_before: ending_before, starting_after: starting_after, limit: limit, lines: lines, reason: reason, refunds: refunds, metadata: metadata, expand: expand, memo: memo, effective_at: effective_at, out_of_band_amount: out_of_band_amount, credit_amount: credit_amount, refund_amount: refund_amount, amount: amount, email_type: email_type, shipping_cost: shipping_cost)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#get_credit_notes_preview_lines\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNoteLinesList.from_json(body), status_code, headers)
    end

    # Retrieve a credit note preview&#39;s line items
    # &lt;p&gt;When retrieving a credit note preview, you’ll get a &lt;strong&gt;lines&lt;/strong&gt; property containing the first handful of those items. This URL you can retrieve the full (paginated) list of line items.&lt;/p&gt;
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param ending_before [String?] A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
    # @optional @param starting_after [String?] A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    # @optional @param limit [Int32?] A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
    # @optional @param lines [Array(Array(CreditNoteLineItemParams))?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refunds [Array(Array(CreditNoteRefundParams))?] Refunds to link to this credit note.
    # @optional @param metadata [Hash(String, Hash(String, String))?] Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    # @optional @param expand [Array(Array(String))?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?] When shipping_cost contains the shipping_rate from the invoice, the shipping_cost is included in the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @return nil
    def get_credit_notes_preview_lines(
      *,
      invoice : String? = nil,
      ending_before : String? = nil,
      starting_after : String? = nil,
      limit : Int32? = nil,
      lines : Array(Array(CreditNoteLineItemParams))? = nil,
      reason : String? = nil,
      refunds : Array(Array(CreditNoteRefundParams))? = nil,
      metadata : Hash(String, Hash(String, String))? = nil,
      expand : Array(Array(String))? = nil,
      memo : String? = nil,
      effective_at : Int32? = nil,
      out_of_band_amount : Int32? = nil,
      credit_amount : Int32? = nil,
      refund_amount : Int32? = nil,
      amount : Int32? = nil,
      email_type : String? = nil,
      shipping_cost : Stripe::CreditNoteShippingCost? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_get_credit_notes_preview_lines(invoice: invoice, ending_before: ending_before, starting_after: starting_after, limit: limit, lines: lines, reason: reason, refunds: refunds, metadata: metadata, expand: expand, memo: memo, effective_at: effective_at, out_of_band_amount: out_of_band_amount, credit_amount: credit_amount, refund_amount: refund_amount, amount: amount, email_type: email_type, shipping_cost: shipping_cost).execute(&block)
    end

    GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_INVOICE = 5000
    GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_ENDING_BEFORE = 5000
    GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_STARTING_AFTER = 5000
    GET_CREDIT_NOTES_PREVIEW_LINES_VALID_VALUES_FOR_REASON = String.static_array("duplicate", "fraudulent", "order_change", "product_unsatisfactory")
    GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_MEMO = 5000
    GET_CREDIT_NOTES_PREVIEW_LINES_VALID_VALUES_FOR_EMAIL_TYPE = String.static_array("credit_note", "none")
    # @return Crest::Request
    def build_api_request_for_get_credit_notes_preview_lines(
      *, 
      invoice : String? = nil, 
      ending_before : String? = nil, 
      starting_after : String? = nil, 
      limit : Int32? = nil, 
      lines : Array(Array(CreditNoteLineItemParams))? = nil, 
      reason : String? = nil, 
      refunds : Array(Array(CreditNoteRefundParams))? = nil, 
      metadata : Hash(String, Hash(String, String))? = nil, 
      expand : Array(Array(String))? = nil, 
      memo : String? = nil, 
      effective_at : Int32? = nil, 
      out_of_band_amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      refund_amount : Int32? = nil, 
      amount : Int32? = nil, 
      email_type : String? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.get_credit_notes_preview_lines ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"invoice\" is required and cannot be null") if invoice.nil?
        unless (_invoice = invoice).nil?
          OpenApi::PrimitiveValidator.validate_max_length("invoice", invoice.to_s.size, GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_INVOICE)
        end
        unless (_ending_before = ending_before).nil?
          OpenApi::PrimitiveValidator.validate_max_length("ending_before", ending_before.to_s.size, GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_ENDING_BEFORE)
        end
        unless (_starting_after = starting_after).nil?
          OpenApi::PrimitiveValidator.validate_max_length("starting_after", starting_after.to_s.size, GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_STARTING_AFTER)
        end
        unless (_limit = limit).nil?
        end
        unless (_lines = lines).nil?
        end
        unless (_reason = reason).nil?
          OpenApi::EnumValidator.validate("reason", _reason, GET_CREDIT_NOTES_PREVIEW_LINES_VALID_VALUES_FOR_REASON)
        end
        unless (_refunds = refunds).nil?
        end
        unless (_metadata = metadata).nil?
        end
        unless (_expand = expand).nil?
        end
        unless (_memo = memo).nil?
          OpenApi::PrimitiveValidator.validate_max_length("memo", memo.to_s.size, GET_CREDIT_NOTES_PREVIEW_LINES_MAX_LENGTH_FOR_MEMO)
        end
        unless (_effective_at = effective_at).nil?
        end
        unless (_out_of_band_amount = out_of_band_amount).nil?
        end
        unless (_credit_amount = credit_amount).nil?
        end
        unless (_refund_amount = refund_amount).nil?
        end
        unless (_amount = amount).nil?
        end
        unless (_email_type = email_type).nil?
          OpenApi::EnumValidator.validate("email_type", _email_type, GET_CREDIT_NOTES_PREVIEW_LINES_VALID_VALUES_FOR_EMAIL_TYPE)
        end
        unless (_shipping_cost = shipping_cost).nil?
          _shipping_cost.validate if _shipping_cost.is_a?(OpenApi::Validatable)
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes/preview/lines"

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new
      query_params["ending_before"] = ending_before.to_s if !ending_before.nil?
      query_params["starting_after"] = starting_after.to_s if !starting_after.nil?
      query_params["limit"] = limit.to_s if !limit.nil?
      query_params["invoice"] = invoice.to_s if !invoice.nil?
      query_params["lines"] = @api_client.build_collection_param(lines, "csv") if !lines.nil? && !lines.empty?
      query_params["reason"] = reason.to_s if !reason.nil?
      query_params["refunds"] = @api_client.build_collection_param(refunds, "csv") if !refunds.nil? && !refunds.empty?
      query_params["metadata"] = metadata.to_s if !metadata.nil?
      query_params["expand"] = @api_client.build_collection_param(expand, "csv") if !expand.nil? && !expand.empty?
      query_params["memo"] = memo.to_s if !memo.nil?
      query_params["effective_at"] = effective_at.to_s if !effective_at.nil?
      query_params["out_of_band_amount"] = out_of_band_amount.to_s if !out_of_band_amount.nil?
      query_params["credit_amount"] = credit_amount.to_s if !credit_amount.nil?
      query_params["refund_amount"] = refund_amount.to_s if !refund_amount.nil?
      query_params["amount"] = amount.to_s if !amount.nil?
      query_params["email_type"] = email_type.to_s if !email_type.nil?
      query_params["shipping_cost"] = shipping_cost.to_s if !shipping_cost.nil?

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = nil

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"GET",
        path: local_var_path,
        operation: "CreditNotesApi.get_credit_notes_preview_lines",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Create a credit note
    # <p>Issue a credit note to adjust the amount of a finalized invoice. A credit note will first reduce the invoice’s <code>amount_remaining</code> (and <code>amount_due</code>), but not below zero. This amount is indicated by the credit note’s <code>pre_payment_amount</code>. The excess amount is indicated by <code>post_payment_amount</code>, and it can result in any combination of the following:</p>  <ul> <li>Refunds: create a new refund (using <code>refund_amount</code>) or link existing refunds (using <code>refunds</code>).</li> <li>Customer balance credit: credit the customer’s balance (using <code>credit_amount</code>) which will be automatically applied to their next invoice when it’s finalized.</li> <li>Outside of Stripe credit: record the amount that is or will be credited outside of Stripe (using <code>out_of_band_amount</code>).</li> </ul>  <p>The sum of refunds, customer balance credits, and outside of Stripe credits must equal the <code>post_payment_amount</code>.</p>  <p>You may issue multiple credit notes for an invoice. Each credit note may increment the invoice’s <code>pre_payment_credit_notes_amount</code>, <code>post_payment_credit_notes_amount</code>, or both, depending on the invoice’s <code>amount_remaining</code> at the time of credit note creation.</p>
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @optional @param lines [Array(Stripe::CreditNoteLineItemParams)?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param metadata [Hash(String, String)?]
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param refunds [Array(Stripe::CreditNoteRefundParams)?] Refunds to link to this credit note.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?]
    # @return [Stripe::CreditNote]
    def post_credit_notes(
      *, 
      invoice : String? = nil, 
      amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      effective_at : Int32? = nil, 
      email_type : String? = nil, 
      expand : Array(String)? = nil, 
      lines : Array(Stripe::CreditNoteLineItemParams)? = nil, 
      memo : String? = nil, 
      metadata : Hash(String, String)? = nil, 
      out_of_band_amount : Int32? = nil, 
      reason : String? = nil, 
      refund_amount : Int32? = nil, 
      refunds : Array(Stripe::CreditNoteRefundParams)? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Stripe::CreditNote
      data, _status_code, _headers = post_credit_notes_with_http_info(invoice: invoice, amount: amount, credit_amount: credit_amount, effective_at: effective_at, email_type: email_type, expand: expand, lines: lines, memo: memo, metadata: metadata, out_of_band_amount: out_of_band_amount, reason: reason, refund_amount: refund_amount, refunds: refunds, shipping_cost: shipping_cost)
      data
    end

    # Create a credit note
    # &lt;p&gt;Issue a credit note to adjust the amount of a finalized invoice. A credit note will first reduce the invoice’s &lt;code&gt;amount_remaining&lt;/code&gt; (and &lt;code&gt;amount_due&lt;/code&gt;), but not below zero. This amount is indicated by the credit note’s &lt;code&gt;pre_payment_amount&lt;/code&gt;. The excess amount is indicated by &lt;code&gt;post_payment_amount&lt;/code&gt;, and it can result in any combination of the following:&lt;/p&gt;  &lt;ul&gt; &lt;li&gt;Refunds: create a new refund (using &lt;code&gt;refund_amount&lt;/code&gt;) or link existing refunds (using &lt;code&gt;refunds&lt;/code&gt;).&lt;/li&gt; &lt;li&gt;Customer balance credit: credit the customer’s balance (using &lt;code&gt;credit_amount&lt;/code&gt;) which will be automatically applied to their next invoice when it’s finalized.&lt;/li&gt; &lt;li&gt;Outside of Stripe credit: record the amount that is or will be credited outside of Stripe (using &lt;code&gt;out_of_band_amount&lt;/code&gt;).&lt;/li&gt; &lt;/ul&gt;  &lt;p&gt;The sum of refunds, customer balance credits, and outside of Stripe credits must equal the &lt;code&gt;post_payment_amount&lt;/code&gt;.&lt;/p&gt;  &lt;p&gt;You may issue multiple credit notes for an invoice. Each credit note may increment the invoice’s &lt;code&gt;pre_payment_credit_notes_amount&lt;/code&gt;, &lt;code&gt;post_payment_credit_notes_amount&lt;/code&gt;, or both, depending on the invoice’s &lt;code&gt;amount_remaining&lt;/code&gt; at the time of credit note creation.&lt;/p&gt;
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @optional @param lines [Array(Stripe::CreditNoteLineItemParams)?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param metadata [Hash(String, String)?]
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param refunds [Array(Stripe::CreditNoteRefundParams)?] Refunds to link to this credit note.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?]
    # @return [Tuple(Stripe::CreditNote, Integer, Hash)] Stripe::CreditNote, response status code and response headers
    def post_credit_notes_with_http_info(
      *, 
      invoice : String? = nil, 
      amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      effective_at : Int32? = nil, 
      email_type : String? = nil, 
      expand : Array(String)? = nil, 
      lines : Array(Stripe::CreditNoteLineItemParams)? = nil, 
      memo : String? = nil, 
      metadata : Hash(String, String)? = nil, 
      out_of_band_amount : Int32? = nil, 
      reason : String? = nil, 
      refund_amount : Int32? = nil, 
      refunds : Array(Stripe::CreditNoteRefundParams)? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Tuple(Stripe::CreditNote, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_post_credit_notes(invoice: invoice, amount: amount, credit_amount: credit_amount, effective_at: effective_at, email_type: email_type, expand: expand, lines: lines, memo: memo, metadata: metadata, out_of_band_amount: out_of_band_amount, reason: reason, refund_amount: refund_amount, refunds: refunds, shipping_cost: shipping_cost)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#post_credit_notes\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNote.from_json(body), status_code, headers)
    end

    # Create a credit note
    # &lt;p&gt;Issue a credit note to adjust the amount of a finalized invoice. A credit note will first reduce the invoice’s &lt;code&gt;amount_remaining&lt;/code&gt; (and &lt;code&gt;amount_due&lt;/code&gt;), but not below zero. This amount is indicated by the credit note’s &lt;code&gt;pre_payment_amount&lt;/code&gt;. The excess amount is indicated by &lt;code&gt;post_payment_amount&lt;/code&gt;, and it can result in any combination of the following:&lt;/p&gt;  &lt;ul&gt; &lt;li&gt;Refunds: create a new refund (using &lt;code&gt;refund_amount&lt;/code&gt;) or link existing refunds (using &lt;code&gt;refunds&lt;/code&gt;).&lt;/li&gt; &lt;li&gt;Customer balance credit: credit the customer’s balance (using &lt;code&gt;credit_amount&lt;/code&gt;) which will be automatically applied to their next invoice when it’s finalized.&lt;/li&gt; &lt;li&gt;Outside of Stripe credit: record the amount that is or will be credited outside of Stripe (using &lt;code&gt;out_of_band_amount&lt;/code&gt;).&lt;/li&gt; &lt;/ul&gt;  &lt;p&gt;The sum of refunds, customer balance credits, and outside of Stripe credits must equal the &lt;code&gt;post_payment_amount&lt;/code&gt;.&lt;/p&gt;  &lt;p&gt;You may issue multiple credit notes for an invoice. Each credit note may increment the invoice’s &lt;code&gt;pre_payment_credit_notes_amount&lt;/code&gt;, &lt;code&gt;post_payment_credit_notes_amount&lt;/code&gt;, or both, depending on the invoice’s &lt;code&gt;amount_remaining&lt;/code&gt; at the time of credit note creation.&lt;/p&gt;
    # @required @param invoice [String?] ID of the invoice.
    # @optional @param amount [Int32?] The integer amount in cents (or local equivalent) representing the total amount of the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param credit_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
    # @optional @param effective_at [Int32?] The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
    # @optional @param email_type [String?] Type of email to send to the customer, one of `credit_note` or `none` and the default is `credit_note`.
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @optional @param lines [Array(Stripe::CreditNoteLineItemParams)?] Line items that make up the credit note. One of `amount`, `lines`, or `shipping_cost` must be provided.
    # @optional @param memo [String?] The credit note's memo appears on the credit note PDF.
    # @optional @param metadata [Hash(String, String)?]
    # @optional @param out_of_band_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount that is credited outside of Stripe.
    # @optional @param reason [String?] Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `order_change`, or `product_unsatisfactory`
    # @optional @param refund_amount [Int32?] The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
    # @optional @param refunds [Array(Stripe::CreditNoteRefundParams)?] Refunds to link to this credit note.
    # @optional @param shipping_cost [Stripe::CreditNoteShippingCost?]
    # @return nil
    def post_credit_notes(
      *,
      invoice : String? = nil,
      amount : Int32? = nil,
      credit_amount : Int32? = nil,
      effective_at : Int32? = nil,
      email_type : String? = nil,
      expand : Array(String)? = nil,
      lines : Array(Stripe::CreditNoteLineItemParams)? = nil,
      memo : String? = nil,
      metadata : Hash(String, String)? = nil,
      out_of_band_amount : Int32? = nil,
      reason : String? = nil,
      refund_amount : Int32? = nil,
      refunds : Array(Stripe::CreditNoteRefundParams)? = nil,
      shipping_cost : Stripe::CreditNoteShippingCost? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_post_credit_notes(invoice: invoice, amount: amount, credit_amount: credit_amount, effective_at: effective_at, email_type: email_type, expand: expand, lines: lines, memo: memo, metadata: metadata, out_of_band_amount: out_of_band_amount, reason: reason, refund_amount: refund_amount, refunds: refunds, shipping_cost: shipping_cost).execute(&block)
    end

    POST_CREDIT_NOTES_MAX_LENGTH_FOR_INVOICE = 5000
    POST_CREDIT_NOTES_VALID_VALUES_FOR_EMAIL_TYPE = String.static_array("credit_note", "none")
    POST_CREDIT_NOTES_MAX_LENGTH_FOR_MEMO = 5000
    POST_CREDIT_NOTES_VALID_VALUES_FOR_REASON = String.static_array("duplicate", "fraudulent", "order_change", "product_unsatisfactory")
    # @return Crest::Request
    def build_api_request_for_post_credit_notes(
      *, 
      invoice : String? = nil, 
      amount : Int32? = nil, 
      credit_amount : Int32? = nil, 
      effective_at : Int32? = nil, 
      email_type : String? = nil, 
      expand : Array(String)? = nil, 
      lines : Array(Stripe::CreditNoteLineItemParams)? = nil, 
      memo : String? = nil, 
      metadata : Hash(String, String)? = nil, 
      out_of_band_amount : Int32? = nil, 
      reason : String? = nil, 
      refund_amount : Int32? = nil, 
      refunds : Array(Stripe::CreditNoteRefundParams)? = nil, 
      shipping_cost : Stripe::CreditNoteShippingCost? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.post_credit_notes ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"invoice\" is required and cannot be null") if invoice.nil?
        unless (_invoice = invoice).nil?
          OpenApi::PrimitiveValidator.validate_max_length("invoice", invoice.to_s.size, POST_CREDIT_NOTES_MAX_LENGTH_FOR_INVOICE)
        end
        unless (_amount = amount).nil?
        end
        unless (_credit_amount = credit_amount).nil?
        end
        unless (_effective_at = effective_at).nil?
        end
        unless (_email_type = email_type).nil?
          OpenApi::EnumValidator.validate("email_type", _email_type, POST_CREDIT_NOTES_VALID_VALUES_FOR_EMAIL_TYPE)
        end
        unless (_expand = expand).nil?
        end
        unless (_lines = lines).nil?
          OpenApi::ContainerValidator.validate(container: _lines) if _lines.is_a?(Array)
        end
        unless (_memo = memo).nil?
          OpenApi::PrimitiveValidator.validate_max_length("memo", memo.to_s.size, POST_CREDIT_NOTES_MAX_LENGTH_FOR_MEMO)
        end
        unless (_metadata = metadata).nil?
        end
        unless (_out_of_band_amount = out_of_band_amount).nil?
        end
        unless (_reason = reason).nil?
          OpenApi::EnumValidator.validate("reason", _reason, POST_CREDIT_NOTES_VALID_VALUES_FOR_REASON)
        end
        unless (_refund_amount = refund_amount).nil?
        end
        unless (_refunds = refunds).nil?
          OpenApi::ContainerValidator.validate(container: _refunds) if _refunds.is_a?(Array)
        end
        unless (_shipping_cost = shipping_cost).nil?
          _shipping_cost.validate if _shipping_cost.is_a?(OpenApi::Validatable)
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes"

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/x-www-form-urlencoded"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = Array(Tuple(String, Crest::ParamsValue)).new
      form_params << Tuple(String, Crest::ParamsValue).new("amount", amount.to_s) if !amount.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("credit_amount", credit_amount.to_s) if !credit_amount.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("effective_at", effective_at.to_s) if !effective_at.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("email_type", email_type.to_s) if !email_type.nil?
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(expand.to_json), "expand")) if !expand.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("invoice", invoice.to_s) if !invoice.nil?
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(lines.to_json), "lines")) if !lines.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("memo", memo.to_s) if !memo.nil?
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(metadata.to_json), "metadata")) if !metadata.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("out_of_band_amount", out_of_band_amount.to_s) if !out_of_band_amount.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("reason", reason.to_s) if !reason.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("refund_amount", refund_amount.to_s) if !refund_amount.nil?
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(refunds.to_json), "refunds")) if !refunds.nil?
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(shipping_cost.to_json), "shipping_cost")) if !shipping_cost.nil?

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"POST",
        path: local_var_path,
        operation: "CreditNotesApi.post_credit_notes",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Update a credit note
    # <p>Updates an existing credit note.</p>
    # @required @param id [String?]
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] Credit note memo.
    # @optional @param metadata [Hash(String, String)?]
    # @return [Stripe::CreditNote]
    def post_credit_notes_id(
      *, 
      id : String? = nil, 
      expand : Array(String)? = nil, 
      memo : String? = nil, 
      metadata : Hash(String, String)? = nil
    ) : Stripe::CreditNote
      data, _status_code, _headers = post_credit_notes_id_with_http_info(id: id, expand: expand, memo: memo, metadata: metadata)
      data
    end

    # Update a credit note
    # &lt;p&gt;Updates an existing credit note.&lt;/p&gt;
    # @required @param id [String?]
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] Credit note memo.
    # @optional @param metadata [Hash(String, String)?]
    # @return [Tuple(Stripe::CreditNote, Integer, Hash)] Stripe::CreditNote, response status code and response headers
    def post_credit_notes_id_with_http_info(
      *, 
      id : String? = nil, 
      expand : Array(String)? = nil, 
      memo : String? = nil, 
      metadata : Hash(String, String)? = nil
    ) : Tuple(Stripe::CreditNote, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_post_credit_notes_id(id: id, expand: expand, memo: memo, metadata: metadata)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#post_credit_notes_id\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNote.from_json(body), status_code, headers)
    end

    # Update a credit note
    # &lt;p&gt;Updates an existing credit note.&lt;/p&gt;
    # @required @param id [String?]
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @optional @param memo [String?] Credit note memo.
    # @optional @param metadata [Hash(String, String)?]
    # @return nil
    def post_credit_notes_id(
      *,
      id : String? = nil,
      expand : Array(String)? = nil,
      memo : String? = nil,
      metadata : Hash(String, String)? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_post_credit_notes_id(id: id, expand: expand, memo: memo, metadata: metadata).execute(&block)
    end

    POST_CREDIT_NOTES_ID_MAX_LENGTH_FOR_ID = 5000
    POST_CREDIT_NOTES_ID_MAX_LENGTH_FOR_MEMO = 5000
    # @return Crest::Request
    def build_api_request_for_post_credit_notes_id(
      *, 
      id : String? = nil, 
      expand : Array(String)? = nil, 
      memo : String? = nil, 
      metadata : Hash(String, String)? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.post_credit_notes_id ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"id\" is required and cannot be null") if id.nil?
        unless (_id = id).nil?
          OpenApi::PrimitiveValidator.validate_max_length("id", id.to_s.size, POST_CREDIT_NOTES_ID_MAX_LENGTH_FOR_ID)
        end
        unless (_expand = expand).nil?
        end
        unless (_memo = memo).nil?
          OpenApi::PrimitiveValidator.validate_max_length("memo", memo.to_s.size, POST_CREDIT_NOTES_ID_MAX_LENGTH_FOR_MEMO)
        end
        unless (_metadata = metadata).nil?
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/x-www-form-urlencoded"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = Array(Tuple(String, Crest::ParamsValue)).new
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(expand.to_json), "expand")) if !expand.nil?
      form_params << Tuple(String, Crest::ParamsValue).new("memo", memo.to_s) if !memo.nil?
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(metadata.to_json), "metadata")) if !metadata.nil?

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"POST",
        path: local_var_path,
        operation: "CreditNotesApi.post_credit_notes_id",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end

    # Void a credit note
    # <p>Marks a credit note as void. Learn more about <a href=\"/docs/billing/invoices/credit-notes#voiding\">voiding credit notes</a>.</p>
    # @required @param id [String?]
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @return [Stripe::CreditNote]
    def post_credit_notes_id_void(
      *, 
      id : String? = nil, 
      expand : Array(String)? = nil
    ) : Stripe::CreditNote
      data, _status_code, _headers = post_credit_notes_id_void_with_http_info(id: id, expand: expand)
      data
    end

    # Void a credit note
    # &lt;p&gt;Marks a credit note as void. Learn more about &lt;a href&#x3D;\&quot;/docs/billing/invoices/credit-notes#voiding\&quot;&gt;voiding credit notes&lt;/a&gt;.&lt;/p&gt;
    # @required @param id [String?]
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @return [Tuple(Stripe::CreditNote, Integer, Hash)] Stripe::CreditNote, response status code and response headers
    def post_credit_notes_id_void_with_http_info(
      *, 
      id : String? = nil, 
      expand : Array(String)? = nil
    ) : Tuple(Stripe::CreditNote, Int32, Hash(String, Array(String) | String))
      request = build_api_request_for_post_credit_notes_id_void(id: id, expand: expand)

      body, status_code, headers = @api_client.execute_api_request(request)

      if debugging?
        Log.debug { "API called: CreditNotesApi#post_credit_notes_id_void\nBody: #{body.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}" }
      end

      Tuple.new(Stripe::CreditNote.from_json(body), status_code, headers)
    end

    # Void a credit note
    # &lt;p&gt;Marks a credit note as void. Learn more about &lt;a href&#x3D;\&quot;/docs/billing/invoices/credit-notes#voiding\&quot;&gt;voiding credit notes&lt;/a&gt;.&lt;/p&gt;
    # @required @param id [String?]
    # @optional @param expand [Array(String)?] Specifies which fields in the response should be expanded.
    # @return nil
    def post_credit_notes_id_void(
      *,
      id : String? = nil,
      expand : Array(String)? = nil,
      &block : Crest::Response ->
    ) : Nil
      build_api_request_for_post_credit_notes_id_void(id: id, expand: expand).execute(&block)
    end

    POST_CREDIT_NOTES_ID_VOID_MAX_LENGTH_FOR_ID = 5000
    # @return Crest::Request
    def build_api_request_for_post_credit_notes_id_void(
      *, 
      id : String? = nil, 
      expand : Array(String)? = nil
    ) : Crest::Request
      if debugging?
        Log.debug { "Calling API: CreditNotesApi.post_credit_notes_id_void ..." }
      end

      if client_side_validation?
        raise ArgumentError.new("\"id\" is required and cannot be null") if id.nil?
        unless (_id = id).nil?
          OpenApi::PrimitiveValidator.validate_max_length("id", id.to_s.size, POST_CREDIT_NOTES_ID_VOID_MAX_LENGTH_FOR_ID)
        end
        unless (_expand = expand).nil?
        end
      end

      # resource path
      local_var_path = "/v1/credit_notes/{id}/void".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # header parameters
      header_params : Hash(String, String) = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/x-www-form-urlencoded"])

      # cookie parameters
      cookie_params : Hash(String, String) = Hash(String, String).new

      # query parameters
      query_params : Hash(String, (String | Array(String) | JSON::Any)) = Hash(String, (String | Array(String) | JSON::Any)).new

      # form parameters
      form_params : Array(Tuple(String, Crest::ParamsValue)) | Nil = Array(Tuple(String, Crest::ParamsValue)).new
      form_params.concat(Crest::ZeroEnumeratedFlatParamsEncoder.flatten_params(JSON.parse(expand.to_json), "expand")) if !expand.nil?

      # http body (model)
      post_body : IO | String | Nil = nil

      # auth_names
      auth_names = ["basicAuth", "bearerAuth"]

      @api_client.build_api_request(
        http_method: :"POST",
        path: local_var_path,
        operation: "CreditNotesApi.post_credit_notes_id_void",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        cookie_params: cookie_params,
        query_params: query_params,
        form_params: form_params
      )
    end
  end
end
