#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::BillingCreditGrantsResourceBalanceCredit
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/billing_credit_grants_resource_balance_credit"

describe Stripe::BillingCreditGrantsResourceBalanceCredit do
  describe "test an instance of BillingCreditGrantsResourceBalanceCredit" do
    it "should create an instance of BillingCreditGrantsResourceBalanceCredit" do
      # instance = Stripe::BillingCreditGrantsResourceBalanceCredit.new
      # (instance).should be_a(Stripe::BillingCreditGrantsResourceBalanceCredit)
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Stripe::BillingCreditGrantsResourceBalanceCredit.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'credits_application_invoice_voided'" do
    it "should work" do
      # instance = Stripe::BillingCreditGrantsResourceBalanceCredit.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute '_type'" do
    it "should work" do
      # instance = Stripe::BillingCreditGrantsResourceBalanceCredit.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::BillingCreditGrantsResourceBalanceCredit::ENUM_VALIDATOR_FOR__TYPE
      # validator.allowable_values.each do |value|
      #   instance._type = value.as(String)
      # end
    end
  end
end
