#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::ConnectEmbeddedFinancialAccountConfigClaim
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/connect_embedded_financial_account_config_claim"

describe Stripe::ConnectEmbeddedFinancialAccountConfigClaim do
  describe "test an instance of ConnectEmbeddedFinancialAccountConfigClaim" do
    it "should create an instance of ConnectEmbeddedFinancialAccountConfigClaim" do
      # instance = Stripe::ConnectEmbeddedFinancialAccountConfigClaim.new
      # (instance).should be_a(Stripe::ConnectEmbeddedFinancialAccountConfigClaim)
    end
  end

  describe "test attribute 'enabled'" do
    it "should work" do
      # instance = Stripe::ConnectEmbeddedFinancialAccountConfigClaim.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'features'" do
    it "should work" do
      # instance = Stripe::ConnectEmbeddedFinancialAccountConfigClaim.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
