#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::DisputeEnhancedEvidenceVisaCompellingEvidence3
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/dispute_enhanced_evidence_visa_compelling_evidence3"

describe Stripe::DisputeEnhancedEvidenceVisaCompellingEvidence3 do
  describe "test an instance of DisputeEnhancedEvidenceVisaCompellingEvidence3" do
    it "should create an instance of DisputeEnhancedEvidenceVisaCompellingEvidence3" do
      # instance = Stripe::DisputeEnhancedEvidenceVisaCompellingEvidence3.new
      # (instance).should be_a(Stripe::DisputeEnhancedEvidenceVisaCompellingEvidence3)
    end
  end

  describe "test attribute 'disputed_transaction'" do
    it "should work" do
      # instance = Stripe::DisputeEnhancedEvidenceVisaCompellingEvidence3.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'prior_undisputed_transactions'" do
    it "should work" do
      # instance = Stripe::DisputeEnhancedEvidenceVisaCompellingEvidence3.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
