#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/dispute_enhanced_eligibility_visa_compelling_evidence3"

describe Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3 do
  describe "test an instance of DisputeEnhancedEligibilityVisaCompellingEvidence3" do
    it "should create an instance of DisputeEnhancedEligibilityVisaCompellingEvidence3" do
      # instance = Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3.new
      # (instance).should be_a(Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3)
    end
  end

  describe "test attribute 'required_actions'" do
    it "should work" do
      # instance = Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3::ENUM_VALIDATOR_FOR_REQUIRED_ACTIONS
      # validator.allowable_values.each do |value|
      #   instance.required_actions = value.as(Array(String))
      # end
    end
  end

  describe "test attribute 'status'" do
    it "should work" do
      # instance = Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::DisputeEnhancedEligibilityVisaCompellingEvidence3::ENUM_VALIDATOR_FOR_STATUS
      # validator.allowable_values.each do |value|
      #   instance.status = value.as(String)
      # end
    end
  end
end
