#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::KlarnaAddress
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/klarna_address"

describe Stripe::KlarnaAddress do
  describe "test an instance of KlarnaAddress" do
    it "should create an instance of KlarnaAddress" do
      # instance = Stripe::KlarnaAddress.new
      # (instance).should be_a(Stripe::KlarnaAddress)
    end
  end

  describe "test attribute 'country'" do
    it "should work" do
      # instance = Stripe::KlarnaAddress.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
