#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::LegalEntityDirectorshipDeclaration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/legal_entity_directorship_declaration"

describe Stripe::LegalEntityDirectorshipDeclaration do
  describe "test an instance of LegalEntityDirectorshipDeclaration" do
    it "should create an instance of LegalEntityDirectorshipDeclaration" do
      # instance = Stripe::LegalEntityDirectorshipDeclaration.new
      # (instance).should be_a(Stripe::LegalEntityDirectorshipDeclaration)
    end
  end

  describe "test attribute 'date'" do
    it "should work" do
      # instance = Stripe::LegalEntityDirectorshipDeclaration.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'ip'" do
    it "should work" do
      # instance = Stripe::LegalEntityDirectorshipDeclaration.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'user_agent'" do
    it "should work" do
      # instance = Stripe::LegalEntityDirectorshipDeclaration.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
