#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PaymentMethodOptionsAlma
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/payment_method_options_alma"

describe Stripe::PaymentMethodOptionsAlma do
  describe "test an instance of PaymentMethodOptionsAlma" do
    it "should create an instance of PaymentMethodOptionsAlma" do
      # instance = Stripe::PaymentMethodOptionsAlma.new
      # (instance).should be_a(Stripe::PaymentMethodOptionsAlma)
    end
  end

  describe "test attribute 'capture_method'" do
    it "should work" do
      # instance = Stripe::PaymentMethodOptionsAlma.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PaymentMethodOptionsAlma::ENUM_VALIDATOR_FOR_CAPTURE_METHOD
      # validator.allowable_values.each do |value|
      #   instance.capture_method = value.as(String)
      # end
    end
  end
end
