#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PaymentMethodDetailsRevolutPay
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/payment_method_details_revolut_pay"

describe Stripe::PaymentMethodDetailsRevolutPay do
  describe "test an instance of PaymentMethodDetailsRevolutPay" do
    it "should create an instance of PaymentMethodDetailsRevolutPay" do
      # instance = Stripe::PaymentMethodDetailsRevolutPay.new
      # (instance).should be_a(Stripe::PaymentMethodDetailsRevolutPay)
    end
  end

  describe "test attribute 'funding'" do
    it "should work" do
      # instance = Stripe::PaymentMethodDetailsRevolutPay.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
