#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PermissionsParam
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/permissions_param"

describe Stripe::PermissionsParam do
  describe "test an instance of PermissionsParam" do
    it "should create an instance of PermissionsParam" do
      # instance = Stripe::PermissionsParam.new
      # (instance).should be_a(Stripe::PermissionsParam)
    end
  end

  describe "test attribute 'update_shipping_details'" do
    it "should work" do
      # instance = Stripe::PermissionsParam.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PermissionsParam::ENUM_VALIDATOR_FOR_UPDATE_SHIPPING_DETAILS
      # validator.allowable_values.each do |value|
      #   instance.update_shipping_details = value.as(String)
      # end
    end
  end
end
