#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PortalResourceScheduleUpdateAtPeriodEnd
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/portal_resource_schedule_update_at_period_end"

describe Stripe::PortalResourceScheduleUpdateAtPeriodEnd do
  describe "test an instance of PortalResourceScheduleUpdateAtPeriodEnd" do
    it "should create an instance of PortalResourceScheduleUpdateAtPeriodEnd" do
      # instance = Stripe::PortalResourceScheduleUpdateAtPeriodEnd.new
      # (instance).should be_a(Stripe::PortalResourceScheduleUpdateAtPeriodEnd)
    end
  end

  describe "test attribute 'conditions'" do
    it "should work" do
      # instance = Stripe::PortalResourceScheduleUpdateAtPeriodEnd.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
