#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PostChargesRequestDestination
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/post_charges_request_destination"

describe Stripe::PostChargesRequestDestination do
  describe "test an instance of PostChargesRequestDestination" do
    it "should create an instance of PostChargesRequestDestination" do
      # instance = Stripe::PostChargesRequestDestination.new
      # (instance).should be_a(Stripe::PostChargesRequestDestination)
    end
  end

  describe "test attribute 'account'" do
    it "should work" do
      # instance = Stripe::PostChargesRequestDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'amount'" do
    it "should work" do
      # instance = Stripe::PostChargesRequestDestination.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
