#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::PostTerminalReadersReaderProcessSetupIntentRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/post_terminal_readers_reader_process_setup_intent_request"

describe Stripe::PostTerminalReadersReaderProcessSetupIntentRequest do
  describe "test an instance of PostTerminalReadersReaderProcessSetupIntentRequest" do
    it "should create an instance of PostTerminalReadersReaderProcessSetupIntentRequest" do
      # instance = Stripe::PostTerminalReadersReaderProcessSetupIntentRequest.new
      # (instance).should be_a(Stripe::PostTerminalReadersReaderProcessSetupIntentRequest)
    end
  end

  describe "test attribute 'allow_redisplay'" do
    it "should work" do
      # instance = Stripe::PostTerminalReadersReaderProcessSetupIntentRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::PostTerminalReadersReaderProcessSetupIntentRequest::ENUM_VALIDATOR_FOR_ALLOW_REDISPLAY
      # validator.allowable_values.each do |value|
      #   instance.allow_redisplay = value.as(String)
      # end
    end
  end

  describe "test attribute 'expand'" do
    it "should work" do
      # instance = Stripe::PostTerminalReadersReaderProcessSetupIntentRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'process_config'" do
    it "should work" do
      # instance = Stripe::PostTerminalReadersReaderProcessSetupIntentRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'setup_intent'" do
    it "should work" do
      # instance = Stripe::PostTerminalReadersReaderProcessSetupIntentRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
