#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::SchedulesPhaseAutomaticTax
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/schedules_phase_automatic_tax"

describe Stripe::SchedulesPhaseAutomaticTax do
  describe "test an instance of SchedulesPhaseAutomaticTax" do
    it "should create an instance of SchedulesPhaseAutomaticTax" do
      # instance = Stripe::SchedulesPhaseAutomaticTax.new
      # (instance).should be_a(Stripe::SchedulesPhaseAutomaticTax)
    end
  end

  describe "test attribute 'disabled_reason'" do
    it "should work" do
      # instance = Stripe::SchedulesPhaseAutomaticTax.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SchedulesPhaseAutomaticTax::ENUM_VALIDATOR_FOR_DISABLED_REASON
      # validator.allowable_values.each do |value|
      #   instance.disabled_reason = value.as(String)
      # end
    end
  end

  describe "test attribute 'enabled'" do
    it "should work" do
      # instance = Stripe::SchedulesPhaseAutomaticTax.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'liability'" do
    it "should work" do
      # instance = Stripe::SchedulesPhaseAutomaticTax.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
