#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::SetupIntentPaymentMethodOptionsBacsDebit1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/setup_intent_payment_method_options_bacs_debit1"

describe Stripe::SetupIntentPaymentMethodOptionsBacsDebit1 do
  describe "test an instance of SetupIntentPaymentMethodOptionsBacsDebit1" do
    it "should create an instance of SetupIntentPaymentMethodOptionsBacsDebit1" do
      # instance = Stripe::SetupIntentPaymentMethodOptionsBacsDebit1.new
      # (instance).should be_a(Stripe::SetupIntentPaymentMethodOptionsBacsDebit1)
    end
  end

  describe "test attribute 'mandate_options'" do
    it "should work" do
      # instance = Stripe::SetupIntentPaymentMethodOptionsBacsDebit1.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'verification_method'" do
    it "should work" do
      # instance = Stripe::SetupIntentPaymentMethodOptionsBacsDebit1.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SetupIntentPaymentMethodOptionsBacsDebit1::ENUM_VALIDATOR_FOR_VERIFICATION_METHOD
      # validator.allowable_values.each do |value|
      #   instance.verification_method = value.as(String)
      # end
    end
  end
end
