#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

# Unit tests for Stripe::SharedTaxUpdateParam
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/stripe/models/shared_tax_update_param"

describe Stripe::SharedTaxUpdateParam do
  describe "test an instance of SharedTaxUpdateParam" do
    it "should create an instance of SharedTaxUpdateParam" do
      # instance = Stripe::SharedTaxUpdateParam.new
      # (instance).should be_a(Stripe::SharedTaxUpdateParam)
    end
  end

  describe "test attribute 'ip_address'" do
    it "should work" do
      # instance = Stripe::SharedTaxUpdateParam.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SharedTaxUpdateParam::ENUM_VALIDATOR_FOR_IP_ADDRESS
      # validator.allowable_values.each do |value|
      #   instance.ip_address = value.as(String)
      # end
    end
  end

  describe "test attribute 'validate_location'" do
    it "should work" do
      # instance = Stripe::SharedTaxUpdateParam.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = Stripe::SharedTaxUpdateParam::ENUM_VALIDATOR_FOR_VALIDATE_LOCATION
      # validator.allowable_values.each do |value|
      #   instance.validate_location = value.as(String)
      # end
    end
  end
end
