#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./billing_credit_grants_resource_applicable_price" 

module Stripe
  # 
  class BillingCreditGrantsResourceScope
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    # The price type that credit grants can apply to. We currently only support the `metered` price type. This refers to prices that have a [Billing Meter](https://docs.stripe.com/api/billing/meter) attached to them. Cannot be used in combination with `prices`.
    @[JSON::Field(key: "price_type", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter price_type : String? = nil
    ERROR_MESSAGE_FOR_PRICE_TYPE = "invalid value for \"price_type\", must be one of [metered]."
    VALID_VALUES_FOR_PRICE_TYPE = String.static_array("metered")



    # The prices that credit grants can apply to. We currently only support `metered` prices. This refers to prices that have a [Billing Meter](https://docs.stripe.com/api/billing/meter) attached to them. Cannot be used in combination with `price_type`.
    @[JSON::Field(key: "prices", type: Array(Stripe::BillingCreditGrantsResourceApplicablePrice)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter prices : Array(Stripe::BillingCreditGrantsResourceApplicablePrice)? = nil



    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @price_type : String? = nil,
      @prices : Array(Stripe::BillingCreditGrantsResourceApplicablePrice)? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_price_type = @price_type).nil?
        invalid_properties.push(ERROR_MESSAGE_FOR_PRICE_TYPE) unless OpenApi::EnumValidator.valid?(_price_type, VALID_VALUES_FOR_PRICE_TYPE)
      end
      unless (_prices = @prices).nil?
        invalid_properties.concat(OpenApi::ContainerValidator.list_invalid_properties_for(key: "prices", container: _prices)) if _prices.is_a?(Array)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_price_type = @price_type).nil?
        return false unless OpenApi::EnumValidator.valid?(_price_type, VALID_VALUES_FOR_PRICE_TYPE)
      end

      unless (_prices = @prices).nil?
        return false if _prices.is_a?(Array) && !OpenApi::ContainerValidator.valid?(container: _prices)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] price_type Object to be assigned
    def price_type=(new_value : String?)

      unless new_value.nil?
        OpenApi::EnumValidator.validate("price_type", new_value, VALID_VALUES_FOR_PRICE_TYPE)
      end

      @price_type = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] prices Object to be assigned
    def prices=(new_value : Array(Stripe::BillingCreditGrantsResourceApplicablePrice)?)

      unless new_value.nil?
        OpenApi::ContainerValidator.validate(container: new_value) if new_value.is_a?(Array)
      end

      @prices = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@price_type, @prices)
  end
end
