#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"


module Stripe
  # 
  class BillingBillResourceInvoicingParentsInvoiceQuoteParent
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    # The quote that generated this invoice
    @[JSON::Field(key: "quote", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    getter quote : String? = nil
    MAX_LENGTH_FOR_QUOTE = 5000


    # End of Required Properties

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @quote : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties.push("\"quote\" is required and cannot be null") if @quote.nil?

      unless (_quote = @quote).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("quote", _quote.to_s.size, MAX_LENGTH_FOR_QUOTE)
          invalid_properties.push(max_length_error)
        end
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      return false if @quote.nil?
      unless (_quote = @quote).nil?
        return false if _quote.to_s.size > MAX_LENGTH_FOR_QUOTE
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] quote Object to be assigned
    def quote=(new_value : String?)

      raise ArgumentError.new("\"quote\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("quote", new_value.to_s.size, MAX_LENGTH_FOR_QUOTE)
      end

      @quote = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@quote)
  end
end
