#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"


module Stripe
  # 
  class ConnectEmbeddedPayoutsFeatures
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    # Whether Stripe user authentication is disabled. This value can only be `true` for accounts where `controller.requirement_collection` is `application` for the account. The default value is the opposite of the `external_account_collection` value. For example, if you don't set `external_account_collection`, it defaults to `true` and `disable_stripe_user_authentication` defaults to `false`.
    @[JSON::Field(key: "disable_stripe_user_authentication", type: Bool?, default: nil, required: true, nullable: false, emit_null: false)]
    getter disable_stripe_user_authentication : Bool? = nil



    # Whether to allow payout schedule to be changed. Defaults to `true` when `controller.losses.payments` is set to `stripe` for the account, otherwise `false`.
    @[JSON::Field(key: "edit_payout_schedule", type: Bool?, default: nil, required: true, nullable: false, emit_null: false)]
    getter edit_payout_schedule : Bool? = nil



    # Whether external account collection is enabled. This feature can only be `false` for accounts where you’re responsible for collecting updated information when requirements are due or change, like Custom accounts. The default value for this feature is `true`.
    @[JSON::Field(key: "external_account_collection", type: Bool?, default: nil, required: true, nullable: false, emit_null: false)]
    getter external_account_collection : Bool? = nil



    # Whether to allow creation of instant payouts. Defaults to `true` when `controller.losses.payments` is set to `stripe` for the account, otherwise `false`.
    @[JSON::Field(key: "instant_payouts", type: Bool?, default: nil, required: true, nullable: false, emit_null: false)]
    getter instant_payouts : Bool? = nil



    # Whether to allow creation of standard payouts. Defaults to `true` when `controller.losses.payments` is set to `stripe` for the account, otherwise `false`.
    @[JSON::Field(key: "standard_payouts", type: Bool?, default: nil, required: true, nullable: false, emit_null: false)]
    getter standard_payouts : Bool? = nil


    # End of Required Properties

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @disable_stripe_user_authentication : Bool? = nil, 
      @edit_payout_schedule : Bool? = nil, 
      @external_account_collection : Bool? = nil, 
      @instant_payouts : Bool? = nil, 
      @standard_payouts : Bool? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties.push("\"disable_stripe_user_authentication\" is required and cannot be null") if @disable_stripe_user_authentication.nil?

      unless (_disable_stripe_user_authentication = @disable_stripe_user_authentication).nil?
      end
      invalid_properties.push("\"edit_payout_schedule\" is required and cannot be null") if @edit_payout_schedule.nil?

      unless (_edit_payout_schedule = @edit_payout_schedule).nil?
      end
      invalid_properties.push("\"external_account_collection\" is required and cannot be null") if @external_account_collection.nil?

      unless (_external_account_collection = @external_account_collection).nil?
      end
      invalid_properties.push("\"instant_payouts\" is required and cannot be null") if @instant_payouts.nil?

      unless (_instant_payouts = @instant_payouts).nil?
      end
      invalid_properties.push("\"standard_payouts\" is required and cannot be null") if @standard_payouts.nil?

      unless (_standard_payouts = @standard_payouts).nil?
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      return false if @disable_stripe_user_authentication.nil?
      unless (_disable_stripe_user_authentication = @disable_stripe_user_authentication).nil?
      end

      return false if @edit_payout_schedule.nil?
      unless (_edit_payout_schedule = @edit_payout_schedule).nil?
      end

      return false if @external_account_collection.nil?
      unless (_external_account_collection = @external_account_collection).nil?
      end

      return false if @instant_payouts.nil?
      unless (_instant_payouts = @instant_payouts).nil?
      end

      return false if @standard_payouts.nil?
      unless (_standard_payouts = @standard_payouts).nil?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] disable_stripe_user_authentication Object to be assigned
    def disable_stripe_user_authentication=(new_value : Bool?)

      raise ArgumentError.new("\"disable_stripe_user_authentication\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @disable_stripe_user_authentication = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] edit_payout_schedule Object to be assigned
    def edit_payout_schedule=(new_value : Bool?)

      raise ArgumentError.new("\"edit_payout_schedule\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @edit_payout_schedule = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] external_account_collection Object to be assigned
    def external_account_collection=(new_value : Bool?)

      raise ArgumentError.new("\"external_account_collection\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @external_account_collection = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] instant_payouts Object to be assigned
    def instant_payouts=(new_value : Bool?)

      raise ArgumentError.new("\"instant_payouts\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @instant_payouts = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] standard_payouts Object to be assigned
    def standard_payouts=(new_value : Bool?)

      raise ArgumentError.new("\"standard_payouts\" is required and cannot be null") if new_value.nil?
      unless new_value.nil?
      end

      @standard_payouts = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@disable_stripe_user_authentication, @edit_payout_schedule, @external_account_collection, @instant_payouts, @standard_payouts)
  end
end
