#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"


module Stripe
  class InvoicesSettingsSpecsCreate
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    @[JSON::Field(key: "hosted_payment_method_save", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter hosted_payment_method_save : String? = nil
    ERROR_MESSAGE_FOR_HOSTED_PAYMENT_METHOD_SAVE = "invalid value for \"hosted_payment_method_save\", must be one of [always, never, offer]."
    VALID_VALUES_FOR_HOSTED_PAYMENT_METHOD_SAVE = String.static_array("always", "never", "offer")



    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @hosted_payment_method_save : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_hosted_payment_method_save = @hosted_payment_method_save).nil?
        invalid_properties.push(ERROR_MESSAGE_FOR_HOSTED_PAYMENT_METHOD_SAVE) unless OpenApi::EnumValidator.valid?(_hosted_payment_method_save, VALID_VALUES_FOR_HOSTED_PAYMENT_METHOD_SAVE)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_hosted_payment_method_save = @hosted_payment_method_save).nil?
        return false unless OpenApi::EnumValidator.valid?(_hosted_payment_method_save, VALID_VALUES_FOR_HOSTED_PAYMENT_METHOD_SAVE)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] hosted_payment_method_save Object to be assigned
    def hosted_payment_method_save=(new_value : String?)

      unless new_value.nil?
        OpenApi::EnumValidator.validate("hosted_payment_method_save", new_value, VALID_VALUES_FOR_HOSTED_PAYMENT_METHOD_SAVE)
      end

      @hosted_payment_method_save = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@hosted_payment_method_save)
  end
end
