#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./issuing_authorization_fleet_fuel_price_data" 
require "./issuing_authorization_fleet_non_fuel_price_data" 
require "./issuing_authorization_fleet_tax_data" 

module Stripe
  # 
  class IssuingAuthorizationFleetReportedBreakdown
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    @[JSON::Field(key: "fuel", type: Stripe::IssuingAuthorizationFleetFuelPriceData?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: fuel.nil? && !fuel_present?)]
    getter fuel : Stripe::IssuingAuthorizationFleetFuelPriceData? = nil

    @[JSON::Field(ignore: true)]
    property? fuel_present : Bool = false


    @[JSON::Field(key: "non_fuel", type: Stripe::IssuingAuthorizationFleetNonFuelPriceData?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: non_fuel.nil? && !non_fuel_present?)]
    getter non_fuel : Stripe::IssuingAuthorizationFleetNonFuelPriceData? = nil

    @[JSON::Field(ignore: true)]
    property? non_fuel_present : Bool = false


    @[JSON::Field(key: "tax", type: Stripe::IssuingAuthorizationFleetTaxData?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: tax.nil? && !tax_present?)]
    getter tax : Stripe::IssuingAuthorizationFleetTaxData? = nil

    @[JSON::Field(ignore: true)]
    property? tax_present : Bool = false


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @fuel : Stripe::IssuingAuthorizationFleetFuelPriceData? = nil,
      @non_fuel : Stripe::IssuingAuthorizationFleetNonFuelPriceData? = nil,
      @tax : Stripe::IssuingAuthorizationFleetTaxData? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_fuel = @fuel).nil?
        invalid_properties.concat(_fuel.list_invalid_properties_for("fuel")) if _fuel.is_a?(OpenApi::Validatable)
      end
      unless (_non_fuel = @non_fuel).nil?
        invalid_properties.concat(_non_fuel.list_invalid_properties_for("non_fuel")) if _non_fuel.is_a?(OpenApi::Validatable)
      end
      unless (_tax = @tax).nil?
        invalid_properties.concat(_tax.list_invalid_properties_for("tax")) if _tax.is_a?(OpenApi::Validatable)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_fuel = @fuel).nil?
        return false if _fuel.is_a?(OpenApi::Validatable) && !_fuel.valid?
      end

      unless (_non_fuel = @non_fuel).nil?
        return false if _non_fuel.is_a?(OpenApi::Validatable) && !_non_fuel.valid?
      end

      unless (_tax = @tax).nil?
        return false if _tax.is_a?(OpenApi::Validatable) && !_tax.valid?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fuel Object to be assigned
    def fuel=(new_value : Stripe::IssuingAuthorizationFleetFuelPriceData?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @fuel = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] non_fuel Object to be assigned
    def non_fuel=(new_value : Stripe::IssuingAuthorizationFleetNonFuelPriceData?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @non_fuel = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tax Object to be assigned
    def tax=(new_value : Stripe::IssuingAuthorizationFleetTaxData?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @tax = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@fuel, @fuel_present, @non_fuel, @non_fuel_present, @tax, @tax_present)
  end
end
