#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"


module Stripe
  # 
  class IssuingTransactionFleetFuelPriceData
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    # Gross fuel amount that should equal Fuel Volume multipled by Fuel Unit Cost, inclusive of taxes.
    @[JSON::Field(key: "gross_amount_decimal", type: BigDecimal?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: gross_amount_decimal.nil? && !gross_amount_decimal_present?)]
    getter gross_amount_decimal : BigDecimal? = nil

    @[JSON::Field(ignore: true)]
    property? gross_amount_decimal_present : Bool = false


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @gross_amount_decimal : BigDecimal? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_gross_amount_decimal = @gross_amount_decimal).nil?
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_gross_amount_decimal = @gross_amount_decimal).nil?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gross_amount_decimal Object to be assigned
    def gross_amount_decimal=(new_value : BigDecimal?)

      unless new_value.nil?
      end

      @gross_amount_decimal = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@gross_amount_decimal, @gross_amount_decimal_present)
  end
end
