#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./payment_method_options_param_blik" 
require "./payment_method_options_us_bank_account" 
require "./setup_intent_param" 
require "./setup_intent_payment_method_options_param" 

module Stripe
  class PaymentMethodOptionsParam
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    @[JSON::Field(key: "acss_debit", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter acss_debit : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "affirm", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter affirm : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "afterpay_clearpay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter afterpay_clearpay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "alipay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter alipay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "alma", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter alma : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "amazon_pay", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter amazon_pay : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "au_becs_debit", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter au_becs_debit : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "bacs_debit", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter bacs_debit : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "bancontact", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter bancontact : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "billie", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter billie : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "blik", type: Stripe::PaymentMethodOptionsParamBlik?, default: nil, required: false, nullable: false, emit_null: false)]
    getter blik : Stripe::PaymentMethodOptionsParamBlik? = nil



    @[JSON::Field(key: "boleto", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter boleto : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "card", type: Stripe::SetupIntentParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter card : Stripe::SetupIntentParam? = nil



    @[JSON::Field(key: "card_present", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter card_present : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "cashapp", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter cashapp : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "crypto", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter crypto : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "customer_balance", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter customer_balance : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "eps", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter eps : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "fpx", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter fpx : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "giropay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter giropay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "grabpay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter grabpay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "ideal", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter ideal : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "interac_present", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter interac_present : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "kakao_pay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter kakao_pay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "klarna", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter klarna : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "konbini", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter konbini : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "kr_card", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter kr_card : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "link", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter link : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "mobilepay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter mobilepay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "multibanco", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter multibanco : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "naver_pay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter naver_pay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "nz_bank_account", type: Stripe::PaymentMethodOptionsParamBlik?, default: nil, required: false, nullable: false, emit_null: false)]
    getter nz_bank_account : Stripe::PaymentMethodOptionsParamBlik? = nil



    @[JSON::Field(key: "oxxo", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter oxxo : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "p24", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter p24 : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "pay_by_bank", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter pay_by_bank : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "payco", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter payco : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "paynow", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter paynow : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "paypal", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter paypal : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "pix", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter pix : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "promptpay", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter promptpay : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "revolut_pay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter revolut_pay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "samsung_pay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter samsung_pay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "satispay", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter satispay : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "sepa_debit", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter sepa_debit : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "sofort", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter sofort : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "swish", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter swish : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "twint", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter twint : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    @[JSON::Field(key: "us_bank_account", type: Stripe::SetupIntentPaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter us_bank_account : Stripe::SetupIntentPaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "wechat_pay", type: Stripe::PaymentMethodOptionsParam?, default: nil, required: false, nullable: false, emit_null: false)]
    getter wechat_pay : Stripe::PaymentMethodOptionsParam? = nil



    @[JSON::Field(key: "zip", type: Stripe::PaymentMethodOptionsUsBankAccount?, default: nil, required: false, nullable: false, emit_null: false)]
    getter zip : Stripe::PaymentMethodOptionsUsBankAccount? = nil



    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @acss_debit : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @affirm : Stripe::PaymentMethodOptionsParam? = nil,
      @afterpay_clearpay : Stripe::PaymentMethodOptionsParam? = nil,
      @alipay : Stripe::PaymentMethodOptionsParam? = nil,
      @alma : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @amazon_pay : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @au_becs_debit : Stripe::PaymentMethodOptionsParam? = nil,
      @bacs_debit : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @bancontact : Stripe::PaymentMethodOptionsParam? = nil,
      @billie : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @blik : Stripe::PaymentMethodOptionsParamBlik? = nil,
      @boleto : Stripe::PaymentMethodOptionsParam? = nil,
      @card : Stripe::SetupIntentParam? = nil,
      @card_present : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @cashapp : Stripe::PaymentMethodOptionsParam? = nil,
      @crypto : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @customer_balance : Stripe::PaymentMethodOptionsParam? = nil,
      @eps : Stripe::PaymentMethodOptionsParam? = nil,
      @fpx : Stripe::PaymentMethodOptionsParam? = nil,
      @giropay : Stripe::PaymentMethodOptionsParam? = nil,
      @grabpay : Stripe::PaymentMethodOptionsParam? = nil,
      @ideal : Stripe::PaymentMethodOptionsParam? = nil,
      @interac_present : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @kakao_pay : Stripe::PaymentMethodOptionsParam? = nil,
      @klarna : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @konbini : Stripe::PaymentMethodOptionsParam? = nil,
      @kr_card : Stripe::PaymentMethodOptionsParam? = nil,
      @link : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @mobilepay : Stripe::PaymentMethodOptionsParam? = nil,
      @multibanco : Stripe::PaymentMethodOptionsParam? = nil,
      @naver_pay : Stripe::PaymentMethodOptionsParam? = nil,
      @nz_bank_account : Stripe::PaymentMethodOptionsParamBlik? = nil,
      @oxxo : Stripe::PaymentMethodOptionsParam? = nil,
      @p24 : Stripe::PaymentMethodOptionsParam? = nil,
      @pay_by_bank : Stripe::PaymentMethodOptionsParam? = nil,
      @payco : Stripe::PaymentMethodOptionsParam? = nil,
      @paynow : Stripe::PaymentMethodOptionsParam? = nil,
      @paypal : Stripe::PaymentMethodOptionsParam? = nil,
      @pix : Stripe::PaymentMethodOptionsParam? = nil,
      @promptpay : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @revolut_pay : Stripe::PaymentMethodOptionsParam? = nil,
      @samsung_pay : Stripe::PaymentMethodOptionsParam? = nil,
      @satispay : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @sepa_debit : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @sofort : Stripe::PaymentMethodOptionsParam? = nil,
      @swish : Stripe::PaymentMethodOptionsParam? = nil,
      @twint : Stripe::PaymentMethodOptionsUsBankAccount? = nil,
      @us_bank_account : Stripe::SetupIntentPaymentMethodOptionsParam? = nil,
      @wechat_pay : Stripe::PaymentMethodOptionsParam? = nil,
      @zip : Stripe::PaymentMethodOptionsUsBankAccount? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_acss_debit = @acss_debit).nil?
        invalid_properties.concat(_acss_debit.list_invalid_properties_for("acss_debit")) if _acss_debit.is_a?(OpenApi::Validatable)
      end
      unless (_affirm = @affirm).nil?
        invalid_properties.concat(_affirm.list_invalid_properties_for("affirm")) if _affirm.is_a?(OpenApi::Validatable)
      end
      unless (_afterpay_clearpay = @afterpay_clearpay).nil?
        invalid_properties.concat(_afterpay_clearpay.list_invalid_properties_for("afterpay_clearpay")) if _afterpay_clearpay.is_a?(OpenApi::Validatable)
      end
      unless (_alipay = @alipay).nil?
        invalid_properties.concat(_alipay.list_invalid_properties_for("alipay")) if _alipay.is_a?(OpenApi::Validatable)
      end
      unless (_alma = @alma).nil?
        invalid_properties.concat(_alma.list_invalid_properties_for("alma")) if _alma.is_a?(OpenApi::Validatable)
      end
      unless (_amazon_pay = @amazon_pay).nil?
        invalid_properties.concat(_amazon_pay.list_invalid_properties_for("amazon_pay")) if _amazon_pay.is_a?(OpenApi::Validatable)
      end
      unless (_au_becs_debit = @au_becs_debit).nil?
        invalid_properties.concat(_au_becs_debit.list_invalid_properties_for("au_becs_debit")) if _au_becs_debit.is_a?(OpenApi::Validatable)
      end
      unless (_bacs_debit = @bacs_debit).nil?
        invalid_properties.concat(_bacs_debit.list_invalid_properties_for("bacs_debit")) if _bacs_debit.is_a?(OpenApi::Validatable)
      end
      unless (_bancontact = @bancontact).nil?
        invalid_properties.concat(_bancontact.list_invalid_properties_for("bancontact")) if _bancontact.is_a?(OpenApi::Validatable)
      end
      unless (_billie = @billie).nil?
        invalid_properties.concat(_billie.list_invalid_properties_for("billie")) if _billie.is_a?(OpenApi::Validatable)
      end
      unless (_blik = @blik).nil?
        invalid_properties.concat(_blik.list_invalid_properties_for("blik")) if _blik.is_a?(OpenApi::Validatable)
      end
      unless (_boleto = @boleto).nil?
        invalid_properties.concat(_boleto.list_invalid_properties_for("boleto")) if _boleto.is_a?(OpenApi::Validatable)
      end
      unless (_card = @card).nil?
        invalid_properties.concat(_card.list_invalid_properties_for("card")) if _card.is_a?(OpenApi::Validatable)
      end
      unless (_card_present = @card_present).nil?
        invalid_properties.concat(_card_present.list_invalid_properties_for("card_present")) if _card_present.is_a?(OpenApi::Validatable)
      end
      unless (_cashapp = @cashapp).nil?
        invalid_properties.concat(_cashapp.list_invalid_properties_for("cashapp")) if _cashapp.is_a?(OpenApi::Validatable)
      end
      unless (_crypto = @crypto).nil?
        invalid_properties.concat(_crypto.list_invalid_properties_for("crypto")) if _crypto.is_a?(OpenApi::Validatable)
      end
      unless (_customer_balance = @customer_balance).nil?
        invalid_properties.concat(_customer_balance.list_invalid_properties_for("customer_balance")) if _customer_balance.is_a?(OpenApi::Validatable)
      end
      unless (_eps = @eps).nil?
        invalid_properties.concat(_eps.list_invalid_properties_for("eps")) if _eps.is_a?(OpenApi::Validatable)
      end
      unless (_fpx = @fpx).nil?
        invalid_properties.concat(_fpx.list_invalid_properties_for("fpx")) if _fpx.is_a?(OpenApi::Validatable)
      end
      unless (_giropay = @giropay).nil?
        invalid_properties.concat(_giropay.list_invalid_properties_for("giropay")) if _giropay.is_a?(OpenApi::Validatable)
      end
      unless (_grabpay = @grabpay).nil?
        invalid_properties.concat(_grabpay.list_invalid_properties_for("grabpay")) if _grabpay.is_a?(OpenApi::Validatable)
      end
      unless (_ideal = @ideal).nil?
        invalid_properties.concat(_ideal.list_invalid_properties_for("ideal")) if _ideal.is_a?(OpenApi::Validatable)
      end
      unless (_interac_present = @interac_present).nil?
        invalid_properties.concat(_interac_present.list_invalid_properties_for("interac_present")) if _interac_present.is_a?(OpenApi::Validatable)
      end
      unless (_kakao_pay = @kakao_pay).nil?
        invalid_properties.concat(_kakao_pay.list_invalid_properties_for("kakao_pay")) if _kakao_pay.is_a?(OpenApi::Validatable)
      end
      unless (_klarna = @klarna).nil?
        invalid_properties.concat(_klarna.list_invalid_properties_for("klarna")) if _klarna.is_a?(OpenApi::Validatable)
      end
      unless (_konbini = @konbini).nil?
        invalid_properties.concat(_konbini.list_invalid_properties_for("konbini")) if _konbini.is_a?(OpenApi::Validatable)
      end
      unless (_kr_card = @kr_card).nil?
        invalid_properties.concat(_kr_card.list_invalid_properties_for("kr_card")) if _kr_card.is_a?(OpenApi::Validatable)
      end
      unless (_link = @link).nil?
        invalid_properties.concat(_link.list_invalid_properties_for("link")) if _link.is_a?(OpenApi::Validatable)
      end
      unless (_mobilepay = @mobilepay).nil?
        invalid_properties.concat(_mobilepay.list_invalid_properties_for("mobilepay")) if _mobilepay.is_a?(OpenApi::Validatable)
      end
      unless (_multibanco = @multibanco).nil?
        invalid_properties.concat(_multibanco.list_invalid_properties_for("multibanco")) if _multibanco.is_a?(OpenApi::Validatable)
      end
      unless (_naver_pay = @naver_pay).nil?
        invalid_properties.concat(_naver_pay.list_invalid_properties_for("naver_pay")) if _naver_pay.is_a?(OpenApi::Validatable)
      end
      unless (_nz_bank_account = @nz_bank_account).nil?
        invalid_properties.concat(_nz_bank_account.list_invalid_properties_for("nz_bank_account")) if _nz_bank_account.is_a?(OpenApi::Validatable)
      end
      unless (_oxxo = @oxxo).nil?
        invalid_properties.concat(_oxxo.list_invalid_properties_for("oxxo")) if _oxxo.is_a?(OpenApi::Validatable)
      end
      unless (_p24 = @p24).nil?
        invalid_properties.concat(_p24.list_invalid_properties_for("p24")) if _p24.is_a?(OpenApi::Validatable)
      end
      unless (_pay_by_bank = @pay_by_bank).nil?
        invalid_properties.concat(_pay_by_bank.list_invalid_properties_for("pay_by_bank")) if _pay_by_bank.is_a?(OpenApi::Validatable)
      end
      unless (_payco = @payco).nil?
        invalid_properties.concat(_payco.list_invalid_properties_for("payco")) if _payco.is_a?(OpenApi::Validatable)
      end
      unless (_paynow = @paynow).nil?
        invalid_properties.concat(_paynow.list_invalid_properties_for("paynow")) if _paynow.is_a?(OpenApi::Validatable)
      end
      unless (_paypal = @paypal).nil?
        invalid_properties.concat(_paypal.list_invalid_properties_for("paypal")) if _paypal.is_a?(OpenApi::Validatable)
      end
      unless (_pix = @pix).nil?
        invalid_properties.concat(_pix.list_invalid_properties_for("pix")) if _pix.is_a?(OpenApi::Validatable)
      end
      unless (_promptpay = @promptpay).nil?
        invalid_properties.concat(_promptpay.list_invalid_properties_for("promptpay")) if _promptpay.is_a?(OpenApi::Validatable)
      end
      unless (_revolut_pay = @revolut_pay).nil?
        invalid_properties.concat(_revolut_pay.list_invalid_properties_for("revolut_pay")) if _revolut_pay.is_a?(OpenApi::Validatable)
      end
      unless (_samsung_pay = @samsung_pay).nil?
        invalid_properties.concat(_samsung_pay.list_invalid_properties_for("samsung_pay")) if _samsung_pay.is_a?(OpenApi::Validatable)
      end
      unless (_satispay = @satispay).nil?
        invalid_properties.concat(_satispay.list_invalid_properties_for("satispay")) if _satispay.is_a?(OpenApi::Validatable)
      end
      unless (_sepa_debit = @sepa_debit).nil?
        invalid_properties.concat(_sepa_debit.list_invalid_properties_for("sepa_debit")) if _sepa_debit.is_a?(OpenApi::Validatable)
      end
      unless (_sofort = @sofort).nil?
        invalid_properties.concat(_sofort.list_invalid_properties_for("sofort")) if _sofort.is_a?(OpenApi::Validatable)
      end
      unless (_swish = @swish).nil?
        invalid_properties.concat(_swish.list_invalid_properties_for("swish")) if _swish.is_a?(OpenApi::Validatable)
      end
      unless (_twint = @twint).nil?
        invalid_properties.concat(_twint.list_invalid_properties_for("twint")) if _twint.is_a?(OpenApi::Validatable)
      end
      unless (_us_bank_account = @us_bank_account).nil?
        invalid_properties.concat(_us_bank_account.list_invalid_properties_for("us_bank_account")) if _us_bank_account.is_a?(OpenApi::Validatable)
      end
      unless (_wechat_pay = @wechat_pay).nil?
        invalid_properties.concat(_wechat_pay.list_invalid_properties_for("wechat_pay")) if _wechat_pay.is_a?(OpenApi::Validatable)
      end
      unless (_zip = @zip).nil?
        invalid_properties.concat(_zip.list_invalid_properties_for("zip")) if _zip.is_a?(OpenApi::Validatable)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_acss_debit = @acss_debit).nil?
        return false if _acss_debit.is_a?(OpenApi::Validatable) && !_acss_debit.valid?
      end

      unless (_affirm = @affirm).nil?
        return false if _affirm.is_a?(OpenApi::Validatable) && !_affirm.valid?
      end

      unless (_afterpay_clearpay = @afterpay_clearpay).nil?
        return false if _afterpay_clearpay.is_a?(OpenApi::Validatable) && !_afterpay_clearpay.valid?
      end

      unless (_alipay = @alipay).nil?
        return false if _alipay.is_a?(OpenApi::Validatable) && !_alipay.valid?
      end

      unless (_alma = @alma).nil?
        return false if _alma.is_a?(OpenApi::Validatable) && !_alma.valid?
      end

      unless (_amazon_pay = @amazon_pay).nil?
        return false if _amazon_pay.is_a?(OpenApi::Validatable) && !_amazon_pay.valid?
      end

      unless (_au_becs_debit = @au_becs_debit).nil?
        return false if _au_becs_debit.is_a?(OpenApi::Validatable) && !_au_becs_debit.valid?
      end

      unless (_bacs_debit = @bacs_debit).nil?
        return false if _bacs_debit.is_a?(OpenApi::Validatable) && !_bacs_debit.valid?
      end

      unless (_bancontact = @bancontact).nil?
        return false if _bancontact.is_a?(OpenApi::Validatable) && !_bancontact.valid?
      end

      unless (_billie = @billie).nil?
        return false if _billie.is_a?(OpenApi::Validatable) && !_billie.valid?
      end

      unless (_blik = @blik).nil?
        return false if _blik.is_a?(OpenApi::Validatable) && !_blik.valid?
      end

      unless (_boleto = @boleto).nil?
        return false if _boleto.is_a?(OpenApi::Validatable) && !_boleto.valid?
      end

      unless (_card = @card).nil?
        return false if _card.is_a?(OpenApi::Validatable) && !_card.valid?
      end

      unless (_card_present = @card_present).nil?
        return false if _card_present.is_a?(OpenApi::Validatable) && !_card_present.valid?
      end

      unless (_cashapp = @cashapp).nil?
        return false if _cashapp.is_a?(OpenApi::Validatable) && !_cashapp.valid?
      end

      unless (_crypto = @crypto).nil?
        return false if _crypto.is_a?(OpenApi::Validatable) && !_crypto.valid?
      end

      unless (_customer_balance = @customer_balance).nil?
        return false if _customer_balance.is_a?(OpenApi::Validatable) && !_customer_balance.valid?
      end

      unless (_eps = @eps).nil?
        return false if _eps.is_a?(OpenApi::Validatable) && !_eps.valid?
      end

      unless (_fpx = @fpx).nil?
        return false if _fpx.is_a?(OpenApi::Validatable) && !_fpx.valid?
      end

      unless (_giropay = @giropay).nil?
        return false if _giropay.is_a?(OpenApi::Validatable) && !_giropay.valid?
      end

      unless (_grabpay = @grabpay).nil?
        return false if _grabpay.is_a?(OpenApi::Validatable) && !_grabpay.valid?
      end

      unless (_ideal = @ideal).nil?
        return false if _ideal.is_a?(OpenApi::Validatable) && !_ideal.valid?
      end

      unless (_interac_present = @interac_present).nil?
        return false if _interac_present.is_a?(OpenApi::Validatable) && !_interac_present.valid?
      end

      unless (_kakao_pay = @kakao_pay).nil?
        return false if _kakao_pay.is_a?(OpenApi::Validatable) && !_kakao_pay.valid?
      end

      unless (_klarna = @klarna).nil?
        return false if _klarna.is_a?(OpenApi::Validatable) && !_klarna.valid?
      end

      unless (_konbini = @konbini).nil?
        return false if _konbini.is_a?(OpenApi::Validatable) && !_konbini.valid?
      end

      unless (_kr_card = @kr_card).nil?
        return false if _kr_card.is_a?(OpenApi::Validatable) && !_kr_card.valid?
      end

      unless (_link = @link).nil?
        return false if _link.is_a?(OpenApi::Validatable) && !_link.valid?
      end

      unless (_mobilepay = @mobilepay).nil?
        return false if _mobilepay.is_a?(OpenApi::Validatable) && !_mobilepay.valid?
      end

      unless (_multibanco = @multibanco).nil?
        return false if _multibanco.is_a?(OpenApi::Validatable) && !_multibanco.valid?
      end

      unless (_naver_pay = @naver_pay).nil?
        return false if _naver_pay.is_a?(OpenApi::Validatable) && !_naver_pay.valid?
      end

      unless (_nz_bank_account = @nz_bank_account).nil?
        return false if _nz_bank_account.is_a?(OpenApi::Validatable) && !_nz_bank_account.valid?
      end

      unless (_oxxo = @oxxo).nil?
        return false if _oxxo.is_a?(OpenApi::Validatable) && !_oxxo.valid?
      end

      unless (_p24 = @p24).nil?
        return false if _p24.is_a?(OpenApi::Validatable) && !_p24.valid?
      end

      unless (_pay_by_bank = @pay_by_bank).nil?
        return false if _pay_by_bank.is_a?(OpenApi::Validatable) && !_pay_by_bank.valid?
      end

      unless (_payco = @payco).nil?
        return false if _payco.is_a?(OpenApi::Validatable) && !_payco.valid?
      end

      unless (_paynow = @paynow).nil?
        return false if _paynow.is_a?(OpenApi::Validatable) && !_paynow.valid?
      end

      unless (_paypal = @paypal).nil?
        return false if _paypal.is_a?(OpenApi::Validatable) && !_paypal.valid?
      end

      unless (_pix = @pix).nil?
        return false if _pix.is_a?(OpenApi::Validatable) && !_pix.valid?
      end

      unless (_promptpay = @promptpay).nil?
        return false if _promptpay.is_a?(OpenApi::Validatable) && !_promptpay.valid?
      end

      unless (_revolut_pay = @revolut_pay).nil?
        return false if _revolut_pay.is_a?(OpenApi::Validatable) && !_revolut_pay.valid?
      end

      unless (_samsung_pay = @samsung_pay).nil?
        return false if _samsung_pay.is_a?(OpenApi::Validatable) && !_samsung_pay.valid?
      end

      unless (_satispay = @satispay).nil?
        return false if _satispay.is_a?(OpenApi::Validatable) && !_satispay.valid?
      end

      unless (_sepa_debit = @sepa_debit).nil?
        return false if _sepa_debit.is_a?(OpenApi::Validatable) && !_sepa_debit.valid?
      end

      unless (_sofort = @sofort).nil?
        return false if _sofort.is_a?(OpenApi::Validatable) && !_sofort.valid?
      end

      unless (_swish = @swish).nil?
        return false if _swish.is_a?(OpenApi::Validatable) && !_swish.valid?
      end

      unless (_twint = @twint).nil?
        return false if _twint.is_a?(OpenApi::Validatable) && !_twint.valid?
      end

      unless (_us_bank_account = @us_bank_account).nil?
        return false if _us_bank_account.is_a?(OpenApi::Validatable) && !_us_bank_account.valid?
      end

      unless (_wechat_pay = @wechat_pay).nil?
        return false if _wechat_pay.is_a?(OpenApi::Validatable) && !_wechat_pay.valid?
      end

      unless (_zip = @zip).nil?
        return false if _zip.is_a?(OpenApi::Validatable) && !_zip.valid?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] acss_debit Object to be assigned
    def acss_debit=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @acss_debit = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] affirm Object to be assigned
    def affirm=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @affirm = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] afterpay_clearpay Object to be assigned
    def afterpay_clearpay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @afterpay_clearpay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] alipay Object to be assigned
    def alipay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @alipay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] alma Object to be assigned
    def alma=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @alma = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] amazon_pay Object to be assigned
    def amazon_pay=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @amazon_pay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] au_becs_debit Object to be assigned
    def au_becs_debit=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @au_becs_debit = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bacs_debit Object to be assigned
    def bacs_debit=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @bacs_debit = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bancontact Object to be assigned
    def bancontact=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @bancontact = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billie Object to be assigned
    def billie=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @billie = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] blik Object to be assigned
    def blik=(new_value : Stripe::PaymentMethodOptionsParamBlik?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @blik = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] boleto Object to be assigned
    def boleto=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @boleto = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] card Object to be assigned
    def card=(new_value : Stripe::SetupIntentParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @card = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] card_present Object to be assigned
    def card_present=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @card_present = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cashapp Object to be assigned
    def cashapp=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @cashapp = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] crypto Object to be assigned
    def crypto=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @crypto = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] customer_balance Object to be assigned
    def customer_balance=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @customer_balance = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] eps Object to be assigned
    def eps=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @eps = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fpx Object to be assigned
    def fpx=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @fpx = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] giropay Object to be assigned
    def giropay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @giropay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] grabpay Object to be assigned
    def grabpay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @grabpay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ideal Object to be assigned
    def ideal=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @ideal = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] interac_present Object to be assigned
    def interac_present=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @interac_present = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kakao_pay Object to be assigned
    def kakao_pay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @kakao_pay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] klarna Object to be assigned
    def klarna=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @klarna = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] konbini Object to be assigned
    def konbini=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @konbini = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kr_card Object to be assigned
    def kr_card=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @kr_card = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] link Object to be assigned
    def link=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @link = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mobilepay Object to be assigned
    def mobilepay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @mobilepay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] multibanco Object to be assigned
    def multibanco=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @multibanco = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] naver_pay Object to be assigned
    def naver_pay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @naver_pay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] nz_bank_account Object to be assigned
    def nz_bank_account=(new_value : Stripe::PaymentMethodOptionsParamBlik?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @nz_bank_account = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] oxxo Object to be assigned
    def oxxo=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @oxxo = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] p24 Object to be assigned
    def p24=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @p24 = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] pay_by_bank Object to be assigned
    def pay_by_bank=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @pay_by_bank = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payco Object to be assigned
    def payco=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @payco = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] paynow Object to be assigned
    def paynow=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @paynow = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] paypal Object to be assigned
    def paypal=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @paypal = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] pix Object to be assigned
    def pix=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @pix = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] promptpay Object to be assigned
    def promptpay=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @promptpay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] revolut_pay Object to be assigned
    def revolut_pay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @revolut_pay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] samsung_pay Object to be assigned
    def samsung_pay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @samsung_pay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] satispay Object to be assigned
    def satispay=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @satispay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sepa_debit Object to be assigned
    def sepa_debit=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @sepa_debit = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sofort Object to be assigned
    def sofort=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @sofort = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] swish Object to be assigned
    def swish=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @swish = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] twint Object to be assigned
    def twint=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @twint = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] us_bank_account Object to be assigned
    def us_bank_account=(new_value : Stripe::SetupIntentPaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @us_bank_account = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] wechat_pay Object to be assigned
    def wechat_pay=(new_value : Stripe::PaymentMethodOptionsParam?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @wechat_pay = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] zip Object to be assigned
    def zip=(new_value : Stripe::PaymentMethodOptionsUsBankAccount?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @zip = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@acss_debit, @affirm, @afterpay_clearpay, @alipay, @alma, @amazon_pay, @au_becs_debit, @bacs_debit, @bancontact, @billie, @blik, @boleto, @card, @card_present, @cashapp, @crypto, @customer_balance, @eps, @fpx, @giropay, @grabpay, @ideal, @interac_present, @kakao_pay, @klarna, @konbini, @kr_card, @link, @mobilepay, @multibanco, @naver_pay, @nz_bank_account, @oxxo, @p24, @pay_by_bank, @payco, @paynow, @paypal, @pix, @promptpay, @revolut_pay, @samsung_pay, @satispay, @sepa_debit, @sofort, @swish, @twint, @us_bank_account, @wechat_pay, @zip)
  end
end
