#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"


module Stripe
  # 
  class PaymentPagesCheckoutSessionPermissions
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    # Determines which entity is allowed to update the shipping details.  Default is `client_only`. Stripe Checkout client will automatically update the shipping details. If set to `server_only`, only your server is allowed to update the shipping details.  When set to `server_only`, you must add the onShippingDetailsChange event handler when initializing the Stripe Checkout client and manually update the shipping details from your server using the Stripe API.
    @[JSON::Field(key: "update_shipping_details", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: update_shipping_details.nil? && !update_shipping_details_present?)]
    getter update_shipping_details : String? = nil
    ERROR_MESSAGE_FOR_UPDATE_SHIPPING_DETAILS = "invalid value for \"update_shipping_details\", must be one of [client_only, server_only]."
    VALID_VALUES_FOR_UPDATE_SHIPPING_DETAILS = String.static_array("client_only", "server_only")

    @[JSON::Field(ignore: true)]
    property? update_shipping_details_present : Bool = false


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @update_shipping_details : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_update_shipping_details = @update_shipping_details).nil?
        invalid_properties.push(ERROR_MESSAGE_FOR_UPDATE_SHIPPING_DETAILS) unless OpenApi::EnumValidator.valid?(_update_shipping_details, VALID_VALUES_FOR_UPDATE_SHIPPING_DETAILS)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_update_shipping_details = @update_shipping_details).nil?
        return false unless OpenApi::EnumValidator.valid?(_update_shipping_details, VALID_VALUES_FOR_UPDATE_SHIPPING_DETAILS)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] update_shipping_details Object to be assigned
    def update_shipping_details=(new_value : String?)

      unless new_value.nil?
        OpenApi::EnumValidator.validate("update_shipping_details", new_value, VALID_VALUES_FOR_UPDATE_SHIPPING_DETAILS)
      end

      @update_shipping_details = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@update_shipping_details, @update_shipping_details_present)
  end
end
