#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./billing_clocks_resource_status_details_status_details" 
require "./test_helpers_test_clock" 

module Stripe
  # ID of the test clock this subscription schedule belongs to.
  class SubscriptionScheduleTestClock
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    # Time at which the object was created. Measured in seconds since the Unix epoch.
    @[JSON::Field(key: "created", type: Int32?, default: nil, required: true, nullable: false, emit_null: false)]
    property created : Int32? = nil



    # Time at which this clock is scheduled to auto delete.
    @[JSON::Field(key: "deletes_after", type: Int32?, default: nil, required: true, nullable: false, emit_null: false)]
    property deletes_after : Int32? = nil



    # Time at which all objects belonging to this clock are frozen.
    @[JSON::Field(key: "frozen_time", type: Int32?, default: nil, required: true, nullable: false, emit_null: false)]
    property frozen_time : Int32? = nil



    # Unique identifier for the object.
    @[JSON::Field(key: "id", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    property id : String? = nil
    MAX_LENGTH_FOR_ID = 5000



    # Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    @[JSON::Field(key: "livemode", type: Bool?, default: nil, required: true, nullable: false, emit_null: false)]
    property livemode : Bool? = nil



    # String representing the object's type. Objects of the same type share the same value.
    @[JSON::Field(key: "object", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    property object : String? = nil
    ERROR_MESSAGE_FOR_OBJECT = "invalid value for \"object\", must be one of [test_helpers.test_clock]."
    VALID_VALUES_FOR_OBJECT = String.static_array("test_helpers.test_clock")



    # The status of the Test Clock.
    @[JSON::Field(key: "status", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    property status : String? = nil
    ERROR_MESSAGE_FOR_STATUS = "invalid value for \"status\", must be one of [advancing, internal_failure, ready]."
    VALID_VALUES_FOR_STATUS = String.static_array("advancing", "internal_failure", "ready")



    @[JSON::Field(key: "status_details", type: Stripe::BillingClocksResourceStatusDetailsStatusDetails?, default: nil, required: true, nullable: false, emit_null: false)]
    property status_details : Stripe::BillingClocksResourceStatusDetailsStatusDetails? = nil


    # End of Required Properties

    # Optional Properties

    # The custom name supplied at creation.
    @[JSON::Field(key: "name", type: String?, default: nil, required: false, nullable: true, emit_null: true, presence: true, ignore_serialize: name.nil? && !name_present?)]
    property name : String? = nil
    MAX_LENGTH_FOR_NAME = 5000

    @[JSON::Field(ignore: true)]
    property? name_present : Bool = false

    # List of class defined in anyOf (OpenAPI v3)
    def self.openapi_any_of
      [
      String,
      Stripe::TestHelpersTestClock
      ]
    end


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @created : Int32? = nil, 
      @deletes_after : Int32? = nil, 
      @frozen_time : Int32? = nil, 
      @id : String? = nil, 
      @livemode : Bool? = nil, 
      @object : String? = nil, 
      @status : String? = nil, 
      @status_details : Stripe::BillingClocksResourceStatusDetailsStatusDetails? = nil,
      # Optional properties
      @name : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      _any_of_found = false
      json_string : String = self.to_json
      _any_of_found = self.class.openapi_any_of.any? do |_class|
        _any_of = begin
          _class.from_json(json_string)
        rescue
          nil
        end

        !_any_of.nil? && _any_of.not_nil!.valid?
      end
      return false if !_any_of_found

      true
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@created, @deletes_after, @frozen_time, @id, @livemode, @object, @status, @status_details, @name, @name_present)
  end
end
