#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"


module Stripe
  class UsCfpbRaceDetailsSpecs
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    @[JSON::Field(key: "race", type: Array(String)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter race : Array(String)? = nil
    ERROR_MESSAGE_FOR_RACE = "invalid value for \"race\", must be one of [african_american, american_indian_or_alaska_native, asian, asian_indian, black_or_african_american, chinese, ethiopian, filipino, guamanian_or_chamorro, haitian, jamaican, japanese, korean, native_hawaiian, native_hawaiian_or_other_pacific_islander, nigerian, other_asian, other_black_or_african_american, other_pacific_islander, prefer_not_to_answer, samoan, somali, vietnamese, white]."
    VALID_VALUES_FOR_RACE = String.static_array("african_american", "american_indian_or_alaska_native", "asian", "asian_indian", "black_or_african_american", "chinese", "ethiopian", "filipino", "guamanian_or_chamorro", "haitian", "jamaican", "japanese", "korean", "native_hawaiian", "native_hawaiian_or_other_pacific_islander", "nigerian", "other_asian", "other_black_or_african_american", "other_pacific_islander", "prefer_not_to_answer", "samoan", "somali", "vietnamese", "white")



    @[JSON::Field(key: "race_other", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter race_other : String? = nil
    MAX_LENGTH_FOR_RACE_OTHER = 5000



    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @race : Array(String)? = nil,
      @race_other : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_race = @race).nil?
        invalid_properties.push(ERROR_MESSAGE_FOR_RACE) unless OpenApi::EnumValidator.valid?(_race, VALID_VALUES_FOR_RACE)
      end
      unless (_race_other = @race_other).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("race_other", _race_other.to_s.size, MAX_LENGTH_FOR_RACE_OTHER)
          invalid_properties.push(max_length_error)
        end
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_race = @race).nil?
        return false unless OpenApi::EnumValidator.valid?(_race, VALID_VALUES_FOR_RACE)
      end

      unless (_race_other = @race_other).nil?
        return false if _race_other.to_s.size > MAX_LENGTH_FOR_RACE_OTHER
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] race Object to be assigned
    def race=(new_value : Array(String)?)

      unless new_value.nil?
        OpenApi::EnumValidator.validate("race", new_value, VALID_VALUES_FOR_RACE)
      end

      @race = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] race_other Object to be assigned
    def race_other=(new_value : String?)

      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("race_other", new_value.to_s.size, MAX_LENGTH_FOR_RACE_OTHER)
      end

      @race_other = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@race, @race_other)
  end
end
