#  Stripe API
#
# The Stripe REST API. Please see https://stripe.com/docs/api for more details.
#
# The version of the OpenAPI document: 2025-06-30.basil
# Contact: dev-platform@stripe.com
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./us_cfpb_ethnicity_details_specs" 
require "./us_cfpb_race_details_specs" 

module Stripe
  class UsCfpbDataSpecs
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json


    # Optional Properties

    @[JSON::Field(key: "ethnicity_details", type: Stripe::UsCfpbEthnicityDetailsSpecs?, default: nil, required: false, nullable: false, emit_null: false)]
    getter ethnicity_details : Stripe::UsCfpbEthnicityDetailsSpecs? = nil



    @[JSON::Field(key: "race_details", type: Stripe::UsCfpbRaceDetailsSpecs?, default: nil, required: false, nullable: false, emit_null: false)]
    getter race_details : Stripe::UsCfpbRaceDetailsSpecs? = nil



    @[JSON::Field(key: "self_identified_gender", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter self_identified_gender : String? = nil
    MAX_LENGTH_FOR_SELF_IDENTIFIED_GENDER = 5000



    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @ethnicity_details : Stripe::UsCfpbEthnicityDetailsSpecs? = nil,
      @race_details : Stripe::UsCfpbRaceDetailsSpecs? = nil,
      @self_identified_gender : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_ethnicity_details = @ethnicity_details).nil?
        invalid_properties.concat(_ethnicity_details.list_invalid_properties_for("ethnicity_details")) if _ethnicity_details.is_a?(OpenApi::Validatable)
      end
      unless (_race_details = @race_details).nil?
        invalid_properties.concat(_race_details.list_invalid_properties_for("race_details")) if _race_details.is_a?(OpenApi::Validatable)
      end
      unless (_self_identified_gender = @self_identified_gender).nil?
        if max_length_error = OpenApi::PrimitiveValidator.max_length_error("self_identified_gender", _self_identified_gender.to_s.size, MAX_LENGTH_FOR_SELF_IDENTIFIED_GENDER)
          invalid_properties.push(max_length_error)
        end
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool

      unless (_ethnicity_details = @ethnicity_details).nil?
        return false if _ethnicity_details.is_a?(OpenApi::Validatable) && !_ethnicity_details.valid?
      end

      unless (_race_details = @race_details).nil?
        return false if _race_details.is_a?(OpenApi::Validatable) && !_race_details.valid?
      end

      unless (_self_identified_gender = @self_identified_gender).nil?
        return false if _self_identified_gender.to_s.size > MAX_LENGTH_FOR_SELF_IDENTIFIED_GENDER
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ethnicity_details Object to be assigned
    def ethnicity_details=(new_value : Stripe::UsCfpbEthnicityDetailsSpecs?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @ethnicity_details = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] race_details Object to be assigned
    def race_details=(new_value : Stripe::UsCfpbRaceDetailsSpecs?)

      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @race_details = new_value
    end
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] self_identified_gender Object to be assigned
    def self_identified_gender=(new_value : String?)

      unless new_value.nil?
        OpenApi::PrimitiveValidator.validate_max_length("self_identified_gender", new_value.to_s.size, MAX_LENGTH_FOR_SELF_IDENTIFIED_GENDER)
      end

      @self_identified_gender = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@ethnicity_details, @race_details, @self_identified_gender)
  end
end
